var selectedText="",focusedInput,startIndex,shouldGoBackHide=0;function goPage2(){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++}function goPage3(a){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++;$("#importPage3Preview").empty();$("#importPage3Preview").append(a)}
function goBack(){$(".progress-bar").css("width","0%");closeAlert();$("#carousel").carousel("prev");$("#carousel").carousel("pause");shouldGoBackHide--;0>=shouldGoBackHide&&$(".carousel-control-prev").css("display","none")}function createNew(){$("#startupDiv").fadeOut();$("#masterDiv").css("overflow","auto");$("#masterDiv").css("height","unset");$("#page1").empty();recreatePage1()}function closeAlert(){$(".alert").alert("close")}
function checkTextIsCorrect(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="page2Error";a.setAttribute("role","alert");var b=document.createElement("p"),d=document.createElement("div"),c=document.createElement("button");c.className="close";c.setAttribute("type","button");c.setAttribute("data-dismiss","alert");c.setAttribute("aria-label","Close");var e=document.createElement("span");c.setAttribute("aria-hidden","true");c.innerHTML="&times;";c.appendChild(e);
d.appendChild(c);a.appendChild(b);a.appendChild(d);(d=$("#importTextarea").val().trim())?(c=$(document.createElement("div")),c.html(d),(d=c.find("#lessonPlanTemplate").html())?(d=d.trim(),0<d.length?(b=document.createElement("div"),b.id="lessonPlanTemplate",$(b).html(d),goPage3(b)):(b.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):
(b.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):(b.appendChild(document.createTextNode("Make sure you entered/uploaded something")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))}
function fileMatchesLayout(a){closeAlert();var b=document.createElement("div");b.className="alert alert-danger fade show";b.id="page2Error";b.setAttribute("role","alert");var d=document.createElement("p"),c=document.createElement("div"),e=document.createElement("button");e.className="close";e.setAttribute("type","button");e.setAttribute("data-dismiss","alert");e.setAttribute("aria-label","Close");var g=document.createElement("span");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";e.appendChild(g);
c.appendChild(e);b.appendChild(d);b.appendChild(c);if(a=a.trim())if(c=$(document.createElement("div")),c.html(a),a=c.find("#lessonPlanTemplate").html()){a=a.trim();if(0<a.length)return!0;d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly"))}else d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly"));else d.appendChild(document.createTextNode("Make sure you entered/uploaded something"));
$("#startupDivPage2 > div").prepend(b);$("#page2Error").slideDown(function(){b.style.display="flex"});return!1}function hideStartupDiv(){$("#page2").empty();$("#page2").html($("#importPage3Preview").html());$("#importPage3Preview").empty();createNew()}
function allowDrop(a){window.File&&window.FileReader&&window.FileList&&window.Blob?($("#importTextarea").css("border","5px dashed grey"),$("#importTextarea").css("border-radius","20px"),a.preventDefault()):alert("Browser doesn't support drag and drop")}function removeDragCSS(){$("#importTextarea").css("border","");$("#importTextarea").css("border-radius","")}
function drop(a){a.preventDefault();removeDragCSS();$(".progress-bar").css("width","0%");$(".progress-bar")[0].classList.add("progress-bar-animated");a=a.dataTransfer.files[0];var b=new FileReader;a.type.match("text/plain")||a.type.match("text/html")?(b.onload=function(){var a=b.result;fileMatchesLayout(a)&&$("#importTextarea").val(a)},b.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"),console.log(a))},b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")}):
a.type.match("application/vnd.ms-excel")||a.type.match("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")?dragAndDropExcel(a):alert("Only .html & .txt accepted format");b.readAsText(a)}
function dragAndDropExcel(a){var b=new FileReader;b.onload=function(a){var b="";a=new Uint8Array(a.target.result);for(var d=a.byteLength,g=0;g<d;g++)b+=String.fromCharCode(a[g]);var l=XLSX.read(b,{type:"binary",cellDates:!0,cellStyles:!0}),m=document.createElement("div");m.id="lessonPlanTemplate";var f=document.createElement("p");f.appendChild(document.createTextNode("Instructors Details"));var h=document.createElement("div");f.className="bold underline";h.id="instructorsDetails";l.SheetNames.forEach(function(a){var b=
"",d=!0;a=l.Sheets[a];for(var c=XLSX.utils.decode_range(a["!ref"]),e=c.s.r;e<=c.e.r;e++)for(var g=c.s.c;g<=c.e.c;g++){var k=-1,n=XLSX.utils.encode_cell({c:g,r:e});if(a[n])if(n=String(a[n].v),-1!==n.indexOf("Week")?k=e:-1!==n.indexOf("Lecture")?k=e:-1!==n.indexOf("Practical")?k=e:-1!==n.indexOf("Tutorial")?k=e:-1!==n.indexOf("Remark")?k=e:console.log(n+" is (probably) Title/Subtitle"),0<=k){$(h).html(b);m.append(f);m.append(h);getAllExcelValues(a,c,e,m);e=c.e.r;break}else n&&(d?(b="<p>"+n+"</p>",d=
!1):b+="<p>"+n+"</p>")}})};b.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"),console.log(a))};b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")};b.readAsArrayBuffer(a)}
function getAllExcelValues(a,b,d,c){for(var e=-1,g=-1,l=-1,m=-1,f=b.s.c;f<=b.e.c;f++){var h=XLSX.utils.encode_cell({c:f,r:d});if(a[h]){h=a[h];var k=String(h.v);-1!==k.indexOf("Week")?e=f:-1!==k.indexOf("Lecture")?g=f:-1!==k.indexOf("Practical")?l=f:-1!==k.indexOf("Tutorial")&&(m=f)}}var p=-1;for(d+=1;d<=b.e.r;d++){var q=document.createElement("div");f=document.createElement("div");var y=document.createElement("p");h=document.createElement("p");q.className="lesson";f.className="lessonHeader";y.className=
"bold";h.className="em";f.appendChild(y);f.appendChild(h);q.appendChild(f);var r=!0;for(f=b.s.c;f<=b.e.c;f++)if(h=XLSX.utils.encode_cell({c:f,r:d}),a[h]){h=a[h];k=String(h.v);r=!1;if(f===e)h.l?"number"==typeof h.v?$(y).html("<a href='"+h.l.target+"' target='_blank'>Week "+h.v+"</a>"):$(y).html("<a href='"+h.l.target+"' target='_blank'>"+h.v+"</a>"):$(y).html("Week "+k);else{var t=document.createElement("div"),u=document.createElement("div"),n=document.createElement("p");u.appendChild(n);var z=document.createElement("div"),
w=document.createElement("p"),x=document.createElement("ul");t.className="lecPracHeader";u.className="lecPracDiv";n.className="bold";z.className="lessonPlanContent";w.className="lessonPlanContentP";f===g?$(n).html("L"):f===l?$(n).html("P"):f===m?$(n).html("T"):$(n).html("R");k=k.trim().split("\n");if(h.l){k=h.v.trim().split("\n");n="";for(var v=0;v<k.length;v++)n+="<li><a href='"+h.l.target+"'>"+k[v]+"</a></li>"}else for(n="",v=0;v<k.length;v++)n+="<li>"+k[v]+"</li>";$(x).html(n);z.appendChild(w);
z.appendChild(x);t.appendChild(u);t.appendChild(z);q.appendChild(t)}c.appendChild(q)}if(r){p=d+1;break}}if(0<p&&p<=b.e.r){e=!0;g=document.createElement("p");l="";g.className="sub";for(d=p;d<=b.e.r;d++)for(f=b.s.c;f<=b.e.c;f++)h=XLSX.utils.encode_cell({c:f,r:d}),a[h]&&(h=a[h],k=String(h.v),e?(l=k,e=!1):l+="<br />"+k);$(g).html(l);c.appendChild(g)}$("#importTextarea").val(c.outerHTML)}function clearImportTextarea(){$("#importTextarea").val("");$(".progress-bar").css("width","0%")}
function makeSortable(){$(".mainSection").sortable({connectWith:".mainSection",items:".contentDivDiv",handle:".contentDivDivDraggableDiv",cancel:".inputDiv, textarea, input, button",update:function(){setActualValue()},axis:"y",cursor:"move",opacity:.5});$("#page1").sortable({items:".mainSection",cancel:":not('.draggableDiv')"})}function removeLessonContent(a){$(a).parent().remove();recreatePage2()}
function addLessonContent(a){var b=document.createElement("div"),d=document.createElement("div");d.className="contentDivDivDraggableDiv progress-bar-striped bg-success";d.style.opacity="0";var c=document.createElement("div");c.className="contentDivDivRight";var e=document.createElement("div"),g=document.createElement("p"),l=document.createElement("select"),m=document.createElement("input"),f=document.createElement("div"),h=document.createElement("div"),k=document.createElement("p"),p=document.createElement("div"),
q=document.createElement("input"),y=document.createElement("p"),r=document.createElement("div"),t=document.createElement("textarea"),u=document.createElement("button"),n=document.createElement("span");b.className="section contentDivDiv";e.className="leftDiv";l.className="form-control";m.className="form-control";f.className="flex rightDiv";h.className="page1Content";u.className="closeImg close";u.setAttribute("onclick","removeLessonContent(this)");u.setAttribute("type","button");u.setAttribute("aria-label",
"Close");n.setAttribute("aria-hidden","true");n.innerHTML="&times;";m.setAttribute("type","color");q.setAttribute("type","text");l.setAttribute("onchange","setActualValue()");m.setAttribute("onchange","setActualValue()");q.setAttribute("onkeyup","inputToDiv(this)");q.setAttribute("onkeydown","inputToDiv(this)");t.setAttribute("onkeyup","inputToDiv(this)");t.setAttribute("onkeydown","inputToDiv(this)");p.contentEditable="true";p.className="inputDiv contenteditableBr form-control";p.setAttribute("onkeyup",
"divToInput(this)");p.setAttribute("onkeydown","divToInput(this)");r.contentEditable="true";r.className="inputDiv form-control";r.setAttribute("onkeyup","divToInput(this)");r.setAttribute("onkeydown","divToInput(this)");$(r).html("<li><br></li>");$(r).keydown(function(a){if(8===a.keyCode&&"<li><br></li>"===$(this).html())return!1});$(q).css("display","none");$(t).css("display","none");$(t).html("<li></li>");$(t).text("<li></li>");var z=document.createElement("option");z.appendChild(document.createTextNode("Lecture"));
z.setAttribute("value","L");var w=document.createElement("option");w.appendChild(document.createTextNode("Practical"));w.setAttribute("value","P");var x=document.createElement("option");x.appendChild(document.createTextNode("Tutorial"));x.setAttribute("value","T");var v=document.createElement("option");v.appendChild(document.createTextNode("Remark"));v.setAttribute("value","R");var A=document.createElement("option");A.appendChild(document.createTextNode("In Course Assessment"));A.setAttribute("value",
"ICA");l.appendChild(z);l.appendChild(w);l.appendChild(x);l.appendChild(v);l.appendChild(A);g.appendChild(document.createTextNode("Lecture/Practical/something"));e.appendChild(g);e.appendChild(l);e.appendChild(m);k.appendChild(document.createTextNode("Content Title"));y.appendChild(document.createTextNode("Content List"));h.appendChild(k);h.appendChild(p);h.appendChild(q);h.appendChild(y);h.appendChild(r);h.appendChild(t);f.appendChild(h);u.appendChild(n);c.appendChild(e);c.appendChild(f);b.appendChild(d);
b.appendChild(c);b.appendChild(u);$(a).before(b);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function addLessonSection(a){var b=document.createElement("div"),d=document.createElement("div"),c=document.createElement("p"),e=document.createElement("div"),g=document.createElement("input"),l=document.createElement("p"),m=document.createElement("div"),f=document.createElement("input"),h=document.createElement("div"),k=document.createElement("div");k.className="contentDivDivDraggableDiv progress-bar-striped bg-success";k.style.opacity="0";var p=document.createElement("div");p.className="contentDivDivRight";
var q=document.createElement("div"),y=document.createElement("p"),r=document.createElement("select"),t=document.createElement("input"),u=document.createElement("div"),n=document.createElement("div"),z=document.createElement("p"),w=document.createElement("div"),x=document.createElement("input"),v=document.createElement("p"),A=document.createElement("div"),E=document.createElement("textarea"),B=document.createElement("button"),C=document.createElement("span"),F=document.createElement("div"),H=document.createElement("p"),
D=document.createElement("button"),G=document.createElement("span");b.className="mainSection section";d.className="lessonTitle";h.className="section contentDivDiv";q.className="leftDiv";r.className="form-control";t.className="form-control";u.className="flex rightDiv";n.className="page1Content";w.className="contenteditableBr form-control";B.className="closeImg close";B.setAttribute("onclick","removeLessonContent(this)");B.setAttribute("type","button");B.setAttribute("aria-label","Close");C.setAttribute("aria-hidden",
"true");C.innerHTML="&times;";F.className="addLessonContent";F.setAttribute("onclick","addLessonContent(this)");D.className="closeImg close";D.setAttribute("onclick","removeLessonContent(this)");D.setAttribute("type","button");D.setAttribute("aria-label","Close");G.setAttribute("aria-hidden","true");G.innerHTML="&times;";g.setAttribute("type","text");g.className="lessonTitleInput form-control";f.setAttribute("type","text");f.className="lessonSubtitleInput form-control";t.setAttribute("type","color");
x.setAttribute("type","text");g.setAttribute("onkeyup","inputToDiv(this)");g.setAttribute("onkeydown","inputToDiv(this)");f.setAttribute("onkeyup","inputToDiv(this)");f.setAttribute("onkeydown","inputToDiv(this)");r.setAttribute("onchange","setActualValue()");t.setAttribute("onchange","setActualValue()");x.setAttribute("onkeyup","inputToDiv(this)");x.setAttribute("onkeydown","inputToDiv(this)");E.setAttribute("onkeyup","inputToDiv(this)");E.setAttribute("onkeydown","inputToDiv(this)");e.contentEditable=
"true";e.className="inputDiv contenteditableBr form-control";e.setAttribute("onkeyup","divToInput(this)");e.setAttribute("onkeydown","divToInput(this)");m.contentEditable="true";m.className="inputDiv contenteditableBr form-control";m.setAttribute("onkeyup","divToInput(this)");m.setAttribute("onkeydown","divToInput(this)");w.contentEditable="true";w.className="inputDiv contenteditableBr form-control";w.setAttribute("onkeyup","divToInput(this)");w.setAttribute("onkeydown","divToInput(this)");A.contentEditable=
"true";A.className="inputDiv form-control";A.setAttribute("onkeyup","divToInput(this)");A.setAttribute("onkeydown","divToInput(this)");$(A).html("<li><br></li>");$(A).keydown(function(a){if(8===a.keyCode&&"<li><br></li>"===$(this).html())return!1});$(g).css("display","none");$(f).css("display","none");$(x).css("display","none");$(E).css("display","none");c.appendChild(document.createTextNode("Lesson Title"));l.appendChild(document.createTextNode("Subtitle Title"));d.appendChild(c);d.appendChild(e);
d.appendChild(g);d.appendChild(l);d.appendChild(m);d.appendChild(f);c=document.createElement("option");c.appendChild(document.createTextNode("Lecture"));c.setAttribute("value","L");e=document.createElement("option");e.appendChild(document.createTextNode("Practical"));e.setAttribute("value","P");g=document.createElement("option");g.appendChild(document.createTextNode("Tutorial"));g.setAttribute("value","T");l=document.createElement("option");l.appendChild(document.createTextNode("Remark"));l.setAttribute("value",
"R");m=document.createElement("option");m.appendChild(document.createTextNode("In Course Assessment"));m.setAttribute("value","ICA");r.appendChild(c);r.appendChild(e);r.appendChild(g);r.appendChild(l);r.appendChild(m);y.appendChild(document.createTextNode("Lecture/Practical/something"));q.appendChild(y);q.appendChild(r);q.appendChild(t);z.appendChild(document.createTextNode("Content Title"));v.appendChild(document.createTextNode("Content List"));n.appendChild(z);n.appendChild(w);n.appendChild(x);
n.appendChild(v);n.appendChild(A);n.appendChild(E);u.appendChild(n);B.appendChild(C);p.appendChild(q);p.appendChild(u);h.appendChild(k);h.appendChild(p);h.appendChild(B);H.appendChild(document.createTextNode("Add new lesson content"));F.appendChild(H);D.appendChild(G);b.appendChild(d);b.appendChild(h);b.appendChild(F);b.appendChild(D);$(a).before(b);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function recreatePage1(){$("#page1").empty();var a=document.createElement("div"),b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));b.className="bold underline";var d=document.createElement("div");d.contentEditable="true";d.className="inputDiv form-control";d.setAttribute("onkeyup","divToInput(this)");d.setAttribute("onkeydown","divToInput(this)");var c=document.createElement("textarea");c.id="paragraphTextarea";c.setAttribute("onkeyup","inputToDiv(this)");
c.setAttribute("onkeydown","inputToDiv(this)");$(c).css("display","none");var e=$("#page2 > #lessonPlanTemplate > #instructorsDetails").html().trim().replace(/\t/g,"");$(d).html(e);$(d).keydown(function(a){if(8===a.keyCode&&"<p><br></p>"===$(this).html())return!1});$(c).val(e);a.appendChild(b);a.appendChild(d);a.appendChild(c);$("#page1").append(a);$(".lesson").each(function(){var a=document.createElement("div");a.className="mainSection section";var b=document.createElement("div");b.className="lessonTitle";
var c=document.createElement("p");c.appendChild(document.createTextNode("Lesson Title"));var d=document.createElement("div");d.contentEditable="true";d.className="inputDiv contenteditableBr form-control";d.setAttribute("onkeyup","divToInput(this)");d.setAttribute("onkeydown","divToInput(this)");var e=document.createElement("input");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.className="lessonTitleInput form-control";$(d).html($(this).find(".lessonHeader").children().eq(0).html());
$(e).val($(this).find(".lessonHeader").children().eq(0).html());$(e).css("display","none");var k=document.createElement("p");k.appendChild(document.createTextNode("Lesson Subtitle"));var p=document.createElement("div");p.contentEditable="true";p.className="inputDiv contenteditableBr form-control";p.setAttribute("onkeyup","divToInput(this)");p.setAttribute("onkeydown","divToInput(this)");var q=document.createElement("input");q.setAttribute("onkeyup","inputToDiv(this)");q.setAttribute("onkeydown","inputToDiv(this)");
q.className="lessonSubtitleInput form-control";$(p).html($(this).find(".lessonHeader").children().eq(1).html());$(q).val($(this).find(".lessonHeader").children().eq(1).text());$(q).css("display","none");b.appendChild(c);b.appendChild(d);b.appendChild(e);b.appendChild(k);b.appendChild(p);b.appendChild(q);a.appendChild(b);$(this).find(".lecPracHeader").each(function(){var b=document.createElement("div");b.className="section contentDivDiv";var d=document.createElement("div");d.className="contentDivDivDraggableDiv progress-bar-striped bg-success";
d.style.opacity="0";var c=document.createElement("div");c.className="contentDivDivRight";var e=document.createElement("div");e.className="leftDiv";var h=document.createElement("p");h.appendChild(document.createTextNode("Lecture/Practical/something"));var f=document.createElement("select");f.setAttribute("onchange","setActualValue()");f.className="form-control";var g=document.createElement("option");g.appendChild(document.createTextNode("Lecture"));g.setAttribute("value","L");var k=document.createElement("option");
k.appendChild(document.createTextNode("Practical"));k.setAttribute("value","P");var l=document.createElement("option");l.appendChild(document.createTextNode("Tutorial"));l.setAttribute("value","T");var m=document.createElement("option");m.appendChild(document.createTextNode("Remark"));m.setAttribute("value","R");var p=document.createElement("option");p.appendChild(document.createTextNode("In Course Assessment"));p.setAttribute("value","ICA");f.appendChild(g);f.appendChild(k);f.appendChild(l);f.appendChild(m);
f.appendChild(p);$(f).val($(this).find(".lecPracDiv :first-child").text());g=document.createElement("input");g.setAttribute("onchange","setActualValue()");g.setAttribute("type","color");g.className="form-control";k=$(this).find(".lecPracDiv").css("background-color");$(g).val(rgb2hex(k));e.appendChild(h);e.appendChild(f);e.appendChild(g);h=document.createElement("div");h.className="flex rightDiv";f=document.createElement("div");f.className="page1Content";g=document.createElement("p");g.appendChild(document.createTextNode("Content Title"));
k=document.createElement("div");k.contentEditable="true";k.className="inputDiv contenteditableBr form-control";k.setAttribute("onkeyup","divToInput(this)");k.setAttribute("onkeydown","divToInput(this)");l=document.createElement("input");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this))");l.setAttribute("type","text");$(k).html($(this).find(".lessonPlanContent .lessonPlanContentP").html());$(l).val($(this).find(".lessonPlanContent .lessonPlanContentP").html());
$(l).css("display","none");m=document.createElement("p");m.appendChild(document.createTextNode("Content List"));p=document.createElement("div");p.contentEditable="true";p.className="inputDiv form-control";p.setAttribute("onkeyup","divToInput(this)");p.setAttribute("onkeydown","divToInput(this)");var q=document.createElement("textarea");q.setAttribute("onkeyup","inputToDiv(this)");q.setAttribute("onkeydown","inputToDiv(this)");$(q).css("display","none");var C=$(this).find(".lessonPlanContent ul").html().trim().replace(/\t/g,
"");$(p).html(C);$(q).val(C);$(p).keydown(function(a){if(8===a.keyCode&&"<li><br></li>"===$(this).html())return!1});f.appendChild(g);f.appendChild(k);f.appendChild(l);f.appendChild(m);f.appendChild(p);f.appendChild(q);h.appendChild(f);f=document.createElement("button");f.className="closeImg close";f.setAttribute("onclick","removeLessonContent(this)");f.setAttribute("type","button");f.setAttribute("aria-label","Close");g=document.createElement("span");g.setAttribute("aria-hidden","true");g.innerHTML=
"&times;";f.appendChild(g);c.appendChild(e);c.appendChild(h);b.appendChild(d);b.appendChild(c);b.appendChild(f);a.appendChild(b)});b=document.createElement("div");b.className="addLessonContent";c=document.createElement("img");d=document.createElement("button");d.className="closeImg close";e=document.createElement("span");b.setAttribute("onclick","addLessonContent(this)");c.setAttribute("src","grass 2.jpg");c.setAttribute("width","30");c.setAttribute("height","30");d.setAttribute("onclick","removeLessonContent(this)");
d.setAttribute("type","button");d.setAttribute("aria-label","Close");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";d.appendChild(e);b.appendChild(c);a.appendChild(b);a.appendChild(d);$("#page1").append(a)});a=document.createElement("div");b=document.createElement("img");a.id="addLessonSection";a.className="addLessonContent";a.setAttribute("onclick","addLessonSection(this)");b.setAttribute("src","grass 2.jpg");b.setAttribute("width","30");b.setAttribute("height","30");a.appendChild(b);
b=document.createElement("div");d=document.createElement("p");d.appendChild(document.createTextNode("Footer"));c=document.createElement("div");c.contentEditable="true";c.className="inputDiv contenteditableBr form-control";c.setAttribute("onkeyup","divToInput(this)");c.setAttribute("onkeydown","divToInput(this)");e=document.createElement("input");e.setAttribute("type","text");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.id="lessonPlanFooter";$(c).html($("#lessonPlanTemplate .sub").html());
$(e).val($("#lessonPlanTemplate .sub").html());$(e).css("display","none");b.appendChild(d);b.appendChild(c);b.appendChild(e);d=document.createElement("br");c=document.createElement("button");c.appendChild(document.createTextNode("Generate HTML"));c.setAttribute("onclick","generateHTML()");c.className="btn btn-primary";e=document.createElement("button");e.appendChild(document.createTextNode("Show All"));e.setAttribute("onclick","showAllInput(this)");e.className="btn";$("#page1").append(a);$("#page1").append(b);
$("#page1").append(d);$("#page1").append(c);$("#page1").append(e);contentEditableBr();makeSortable()}
function recreatePage2(){$("#page2").empty();var a=document.createElement("div");a.id="lessonPlanTemplate";var b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));var d=document.createElement("div"),c=$("#paragraphTextarea").val();$(d).html(c);b.className="bold underline";d.id="instructorsDetails";a.append(b);a.append(d);$(".mainSection").each(function(){var b=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(d).html($(this).find(".lessonTitleInput").val());
var m=document.createElement("p");$(m).html($(this).find(".lessonSubtitleInput").val());b.className="lesson";c.className="lessonHeader";d.className="bold";m.className="em";c.appendChild(d);c.appendChild(m);b.appendChild(c);$(this).find(".contentDivDiv").each(function(){var a=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(c).css("background-color",$(this).find(".leftDiv input:nth-child(3)").val());$(d).html($(this).find(".leftDiv :nth-child(2)").val());
c.appendChild(d);var e=document.createElement("div"),g=document.createElement("p");$(g).html($(this).find(".rightDiv .page1Content :nth-child(2)").html());var l=document.createElement("ul"),m=$(this).find(".rightDiv .page1Content :nth-child(5)").html();$(l).html(m);a.className="lecPracHeader";c.className="lecPracDiv";d.className="bold";e.className="lessonPlanContent";g.className="lessonPlanContentP";e.appendChild(g);e.appendChild(l);a.appendChild(c);a.appendChild(e);b.appendChild(a)});a.append(b)});
b=document.createElement("p");$(b).html($("#lessonPlanFooter").val());b.className="sub";a.append(b);$("#page2").append(a)}function setInputValue(){recreatePage1()}function setActualValue(){recreatePage2()}function generateHTML(){$("#popupDiv").modal("show");$("#popup .modal-body textarea").val($("#page2").html().trim())}function closePopup(){$("#popupDiv").modal("hide");$("#popup .generateHTMLRedText").css("display","none")}
function copyToClipboard(){$("#popup .modal-body textarea")[0].select();document.execCommand("copy");$("#popup .generateHTMLRedText").css("display","block")}function copyCommand(){var a=document.createElement("textarea");$(a).text(selectedText);$("#masterDiv").append(a);$(a)[0].select();document.execCommand("copy");$(a).remove()}function promptLink(){0<selectedText.length&&($("#linkInput").val(""),$("#linkBoxDiv").modal("show"))}
function hideLinkBox(){$("#linkBoxDiv").modal("hide");changeInputBoxSelection(1)}
function changeInputBoxSelection(a){$(".dropdown-menu > .active.dropdown-item")[0].classList.remove("active");var b=$("#linkBoxOptions"),d=$("#linkInput");switch(a){case 1:b.text("Webpage");d[0].setAttribute("placeholder","https://");d.val("");$(".dropdown-menu > a:first-child")[0].classList.add("active");break;case 2:b.text("Email");d[0].setAttribute("placeholder","example@nyp.edu.sg");/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&d.val(htmlEncode(selectedText));
$(".dropdown-menu > a:nth-child(2)")[0].classList.add("active");break;case 3:b.text("Javascript"),d[0].setAttribute("placeholder","alert('Hello')"),d.val(""),$(".dropdown-menu > a:nth-child(4)")[0].classList.add("active")}}
function checkAndDisplayAlert(){var a=document.createElement("div");a.className="alert alert-warning fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var b=document.createElement("p"),d=document.createElement("div"),c=document.createElement("button");c.className="close";c.setAttribute("type","button");c.setAttribute("data-dismiss","alert");c.setAttribute("aria-label","Close");var e=document.createElement("span");c.setAttribute("aria-hidden","true");c.innerHTML="&times;";c.appendChild(e);
d.appendChild(c);a.appendChild(b);a.appendChild(d);d=$("#linkInput").val();c=$("#linkBoxOptions").text();"Webpage"===c?/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(d)?closeAlert():(closeAlert(),b.appendChild(document.createTextNode("The URL entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):"Email"===c&&(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(d)?
closeAlert():(closeAlert(),b.appendChild(document.createTextNode("The email entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)))}function whichLinkSelection(){var a=$("#linkBoxOptions").text();if("Webpage"===a)return"";if("Email"===a)return"mailto:";if("Javascript"===a)return"javascript:";alert("Unexpected error");return null}
function convertToLink(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var b=document.createElement("p"),d=document.createElement("div"),c=document.createElement("button");c.className="close";c.setAttribute("type","button");c.setAttribute("data-dismiss","alert");c.setAttribute("aria-label","Close");var e=document.createElement("span");c.setAttribute("aria-hidden","true");c.innerHTML="&times;";c.appendChild(e);
d.appendChild(c);a.appendChild(b);a.appendChild(d);if(d=$("#linkInput").val()){if(""===whichLinkSelection()){if(!/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(d)&&!confirm("The URL entered does not match the format. Do you want to continue?"))return b.appendChild(document.createTextNode("The URL entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1}else if("mailto:"===
whichLinkSelection()&&!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&!confirm("The email entered does not match the format. Do you want to continue?"))return b.appendChild(document.createTextNode("The email entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1;c=htmlEncode(selectedText);
var g=focusedInput;e=g.html();d=whichLinkSelection()?"<a href='"+whichLinkSelection()+$("#linkInput").val()+"' target='_blank'>"+c+"</a>":"<a href='"+$("#linkInput").val()+"' target='_blank'>"+c+"</a>";startIndex=g.next().val().indexOf(c);var l=escape("<a href="),m=escape("</a>");(new RegExp("("+l+").*("+escape(c)+").*("+m+")")).test(escape(g.next().val()))?(b.appendChild(document.createTextNode("Error! You already made this a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):-1!==
startIndex?(a=e.substring(0,startIndex),b=e.substring(startIndex+c.length),a=a+d+b,focusedInput.next().val(a),focusedInput.html(focusedInput.next().val()),setActualValue()):(b.appendChild(document.createTextNode("Error! Make sure the text selected is not overlapping with another link.")),$("#linkBox > .modal-content > .modal-body").prepend(a));hideLinkBox()}else b.appendChild(document.createTextNode("Please enter a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)}
function divToInput(a){$(a).next().val(a.innerHTML);setActualValue()}function inputToDiv(a){$(a).prev().html(a.value);setActualValue()}var notClicked=!0;function showAllInput(a){notClicked?($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"),a.innerHTML="Hide All",notClicked=!1):($(".inputDiv").next().css("display","none"),$("textarea:not(#popup > textarea)").css("display","none"),a.innerHTML="Show All",notClicked=!0)}
function checkEnterKey(a){if(13===a.keyCode)return document.execCommand("insertHTML",!1,"<br /><br />"),!1}function contentEditableBr(){$(document).off("keydown",".contenteditableBr",checkEnterKey);$(document).on("keydown",".contenteditableBr",checkEnterKey)}function selectAll(a){a.setSelectionRange(0,a.value.length)}
$(function(){$(".carousel-control-prev").css("display","none");clearImportTextarea();if($(".inputDiv").addEventListener)$(".inputDiv").addEventListener("contextmenu",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var b=window.getSelection();b.rangeCount&&(startIndex=b.focusOffset)}else"undefined"!=typeof document.selection&&"Text"==document.selection.type&&(startIndex=b.focusOffset);window.getSelection?selectedText=window.getSelection().toString():document.selection&&
"Control"!=document.selection.type&&(selectedText=document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}));a.preventDefault()},!1);else $("body").on("contextmenu",".inputDiv",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var b=window.getSelection();b.rangeCount&&(startIndex=b.focusOffset)}else"undefined"!=typeof document.selection&&"Text"==document.selection.type&&(startIndex=
b.focusOffset);window.getSelection?selectedText=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(selectedText=document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}));window.event.returnValue=!1});$(document).bind("click",function(a){$("#rightClickMenu").css("display","none")});$(document).on("mouseover",".contentDivDivDraggableDiv",function(){$(this).stop(!0,
!0);$(this).animate({opacity:1,queue:!1},300)});$(document).on("mouseout",".contentDivDivDraggableDiv",function(){$(this).animate({opacity:0},300)});contentEditableBr()});var hexDigits="0123456789abcdef".split("");function rgb2hex(a){return(a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/))?"#"+hex(a[1])+hex(a[2])+hex(a[3]):"#000000"}function hex(a){return isNaN(a)?"00":hexDigits[(a-a%16)/16]+hexDigits[a%16]}function htmlEncode(a){return $("<div/>").text(a).html()}
function htmlDecode(a){return a.replace(/&#(\d+);?/g,function(a,d){return String.fromCharCode(d)})};
