var selectedText="",focusedInput,startIndex,shouldGoBackHide=0;function goPage2(){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++}function goPage3(a){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++;$("#importPage3Preview").empty();$("#importPage3Preview").append(a)}
function goBack(){$(".progress-bar").css("width","0%");closeAlert();$("#carousel").carousel("prev");$("#carousel").carousel("pause");shouldGoBackHide--;0>=shouldGoBackHide&&$(".carousel-control-prev").css("display","none")}function createNew(){$("#startupDiv").fadeOut();$("#masterDiv").css("overflow","auto");$("#masterDiv").css("height","unset");$("#page1").empty();recreatePage1()}function closeAlert(){$(".alert").alert("close")}
function checkTextIsCorrect(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="page2Error";a.setAttribute("role","alert");var b=document.createElement("p"),c=document.createElement("div"),d=document.createElement("button");d.className="close";d.setAttribute("type","button");d.setAttribute("data-dismiss","alert");d.setAttribute("aria-label","Close");var e=document.createElement("span");d.setAttribute("aria-hidden","true");d.innerHTML="&times;";d.appendChild(e);
c.appendChild(d);a.appendChild(b);a.appendChild(c);(c=$("#importTextarea").val().trim())?(d=$(document.createElement("div")),d.html(c),(c=d.find("#lessonPlanTemplate").html())?(c=c.trim(),0<c.length?(b=document.createElement("div"),b.id="lessonPlanTemplate",$(b).html(c),goPage3(b)):(b.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):
(b.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):(b.appendChild(document.createTextNode("Make sure you entered/uploaded something")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))}
function fileMatchesLayout(a){closeAlert();var b=document.createElement("div");b.className="alert alert-danger fade show";b.id="page2Error";b.setAttribute("role","alert");var c=document.createElement("p"),d=document.createElement("div"),e=document.createElement("button");e.className="close";e.setAttribute("type","button");e.setAttribute("data-dismiss","alert");e.setAttribute("aria-label","Close");var f=document.createElement("span");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";e.appendChild(f);
d.appendChild(e);b.appendChild(c);b.appendChild(d);if(a=a.trim())if(d=$(document.createElement("div")),d.html(a),a=d.find("#lessonPlanTemplate").html()){a=a.trim();if(0<a.length)return!0;c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly"))}else c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly"));else c.appendChild(document.createTextNode("Make sure you entered/uploaded something"));
$("#startupDivPage2 > div").prepend(b);$("#page2Error").slideDown(function(){b.style.display="flex"});return!1}function hideStartupDiv(){$("#page2").empty();$("#page2").html($("#importPage3Preview").html());$("#importPage3Preview").empty();createNew()}
function allowDrop(a){window.File&&window.FileReader&&window.FileList&&window.Blob?($("#importTextarea").css("border","5px dashed grey"),$("#importTextarea").css("border-radius","20px"),a.preventDefault()):alert("Browser doesn't support drag and drop")}function removeDragCSS(){$("#importTextarea").css("border","");$("#importTextarea").css("border-radius","")}
function drop(a){a.preventDefault();removeDragCSS();$(".progress-bar").css("width","0%");$(".progress-bar")[0].classList.add("progress-bar-animated");a=a.dataTransfer.files[0];var b=new FileReader;a.type.match("text/plain")||a.type.match("text/html")?(b.onload=function(){var a=b.result;fileMatchesLayout(a)&&$("#importTextarea").val(a)},b.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"),console.log(a))},b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")}):
a.type.match("application/vnd.ms-excel")||a.type.match("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")?dragAndDropExcel(a):alert("Only .html, .txt & .xls(x) is the accepted file format");b.readAsText(a)}
function dragAndDropExcel(a){var b=new FileReader;b.onload=function(a){var b="";a=new Uint8Array(a.target.result);for(var c=a.byteLength,f=0;f<c;f++)b+=String.fromCharCode(a[f]);var k=XLSX.read(b,{type:"binary",cellDates:!0,cellStyles:!0}),m=document.createElement("div");m.id="lessonPlanTemplate";var g=document.createElement("p");g.appendChild(document.createTextNode("Instructors Details"));var h=document.createElement("div");g.className="bold underline";h.id="instructorsDetails";k.SheetNames.forEach(function(a){var b=
"",c=!0;a=k.Sheets[a];for(var d=XLSX.utils.decode_range(a["!ref"]),e=d.s.r;e<=d.e.r;e++)for(var f=d.s.c;f<=d.e.c;f++){var t=-1,p=XLSX.utils.encode_cell({c:f,r:e});if(a[p])if(p=String(a[p].v),-1!==p.indexOf("Week")?t=e:-1!==p.indexOf("Lecture")?t=e:-1!==p.indexOf("Practical")?t=e:-1!==p.indexOf("Tutorial")?t=e:-1!==p.indexOf("Remark")&&(t=e),0<=t){$(h).html(b);m.append(g);m.append(h);getAllExcelValues(a,d,e,m);e=d.e.r;break}else p&&(c?(b="<p>"+p+"</p>",c=!1):b+="<p>"+p+"</p>")}})};b.onprogress=function(a){a.lengthComputable&&
(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"))};b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")};b.readAsArrayBuffer(a)}
function getAllExcelValues(a,b,c,d){for(var e=-1,f=-1,k=-1,m=-1,g=b.s.c;g<=b.e.c;g++){var h=XLSX.utils.encode_cell({c:g,r:c});a[h]&&(h=String(a[h].v),-1!==h.indexOf("Week")?e=g:-1!==h.indexOf("Lecture")?f=g:-1!==h.indexOf("Practical")?k=g:-1!==h.indexOf("Tutorial")&&(m=g))}g=-1;for(c+=1;c<=b.e.r;c++){h=document.createElement("div");var t=document.createElement("div"),v=document.createElement("p"),l=document.createElement("p");h.className="lesson";t.className="lessonHeader";v.className="bold";l.className=
"em";t.appendChild(v);t.appendChild(l);h.appendChild(t);t=!0;for(l=b.s.c;l<=b.e.c;l++){var r=XLSX.utils.encode_cell({c:l,r:c});if(a[r]){var q=a[r],u=String(q.v);t=!1;if(l===e)q.l?"number"==typeof q.v?$(v).html("<a href='"+q.l.display+"' target='_blank'>Week "+q.v+"</a>"):$(v).html("<a href='"+q.l.display+"' target='_blank'>"+q.v+"</a>"):$(v).html("Week "+u);else{r=document.createElement("div");var w=document.createElement("div"),p=document.createElement("p");w.appendChild(p);var z=document.createElement("div"),
n=document.createElement("p"),x=document.createElement("ul");r.className="lecPracHeader";w.className="lecPracDiv";p.className="bold";z.className="lessonPlanContent";n.className="lessonPlanContentP";l===f?$(p).html("L"):l===k?$(p).html("P"):l===m?$(p).html("T"):$(p).html("R");u=u.trim().split("\n");p="";if(q.l){u=q.v.trim().split("\n");for(var y=0;y<u.length;y++)q.l.display?p+="<li><a href='"+q.l.display+"' target='_blank'>"+u[y]+"</a></li>":(console.log("Couldn't add link to "+u[y]+" due to error"),
p+="<li>"+u[y]+"</li>")}else for(q=0;q<u.length;q++)p+="<li>"+u[q]+"</li>";$(x).html(p);z.appendChild(n);z.appendChild(x);r.appendChild(w);r.appendChild(z);h.appendChild(r)}d.appendChild(h)}}if(t){g=c+1;break}}if(0<g&&g<=b.e.r){e=!0;f=document.createElement("p");k="";f.className="sub";for(m=g;m<=b.e.r;m++)for(g=b.s.c;g<=b.e.c;g++)c=XLSX.utils.encode_cell({c:g,r:m}),a[c]&&(c=String(a[c].v),e?(k=c,e=!1):k+="<br />"+c);$(f).html(k);d.appendChild(f)}$("#importTextarea").val(d.outerHTML)}
function clearImportTextarea(){$("#importTextarea").val("");$(".progress-bar").css("width","0%")}function makeSortable(){$(".mainSection").sortable({connectWith:".mainSection",items:".contentDivDiv",handle:".contentDivDivDraggableDiv",cancel:".inputDiv, textarea, input, button",update:function(){setActualValue()},axis:"y",cursor:"move",opacity:.5});$("#page1").sortable({items:".mainSection",cancel:":not('.draggableDiv')"})}function removeLessonContent(a){$(a).parent().remove();recreatePage2()}
function addLessonContent(a){var b=document.createElement("div"),c=document.createElement("div");c.className="contentDivDivDraggableDiv progress-bar-striped bg-success";c.style.opacity="0";var d=document.createElement("div");d.className="contentDivDivRight";var e=document.createElement("div"),f=document.createElement("p"),k=document.createElement("select"),m=document.createElement("input"),g=document.createElement("div"),h=document.createElement("div"),t=document.createElement("p"),v=document.createElement("div"),
l=document.createElement("input"),r=document.createElement("p"),q=document.createElement("div"),u=document.createElement("textarea"),w=document.createElement("button"),p=document.createElement("span");b.className="section contentDivDiv";e.className="leftDiv";k.className="form-control";m.className="form-control";g.className="flex rightDiv";h.className="page1Content";w.className="closeImg close";w.setAttribute("onclick","removeLessonContent(this)");w.setAttribute("type","button");w.setAttribute("aria-label",
"Close");p.setAttribute("aria-hidden","true");p.innerHTML="&times;";m.setAttribute("type","color");l.setAttribute("type","text");k.setAttribute("onchange","setActualValue()");m.setAttribute("onchange","setActualValue()");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this)");u.setAttribute("onkeyup","inputToDiv(this)");u.setAttribute("onkeydown","inputToDiv(this)");v.contentEditable="true";v.className="inputDiv contenteditableBr form-control";v.setAttribute("onkeyup",
"divToInput(this)");v.setAttribute("onkeydown","divToInput(this)");q.contentEditable="true";q.className="inputDiv form-control";q.setAttribute("onkeyup","divToInput(this)");q.setAttribute("onkeydown","divToInput(this)");$(q).html("<ul><li><br></li></ul>");$(q).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});$(l).css("display","none");$(u).css("display","none");$(u).html("<li></li>");$(u).text("<li></li>");var z=document.createElement("option");z.appendChild(document.createTextNode("Lecture"));
z.setAttribute("value","L");var n=document.createElement("option");n.appendChild(document.createTextNode("Practical"));n.setAttribute("value","P");var x=document.createElement("option");x.appendChild(document.createTextNode("Tutorial"));x.setAttribute("value","T");var y=document.createElement("option");y.appendChild(document.createTextNode("Remark"));y.setAttribute("value","R");var A=document.createElement("option");A.appendChild(document.createTextNode("In Course Assessment"));A.setAttribute("value",
"ICA");k.appendChild(z);k.appendChild(n);k.appendChild(x);k.appendChild(y);k.appendChild(A);f.appendChild(document.createTextNode("Lecture/Practical/something"));e.appendChild(f);e.appendChild(k);e.appendChild(m);t.appendChild(document.createTextNode("Content Title"));r.appendChild(document.createTextNode("Content List"));h.appendChild(t);h.appendChild(v);h.appendChild(l);h.appendChild(r);h.appendChild(q);h.appendChild(u);g.appendChild(h);w.appendChild(p);d.appendChild(e);d.appendChild(g);b.appendChild(c);
b.appendChild(d);b.appendChild(w);$(a).before(b);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function addLessonSection(a){var b=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p"),e=document.createElement("div"),f=document.createElement("input"),k=document.createElement("p"),m=document.createElement("div"),g=document.createElement("input"),h=document.createElement("div"),t=document.createElement("div");t.className="contentDivDivDraggableDiv progress-bar-striped bg-success";t.style.opacity="0";var v=document.createElement("div");v.className="contentDivDivRight";
var l=document.createElement("div"),r=document.createElement("p"),q=document.createElement("select"),u=document.createElement("input"),w=document.createElement("div"),p=document.createElement("div"),z=document.createElement("p"),n=document.createElement("div"),x=document.createElement("input"),y=document.createElement("p"),A=document.createElement("div");document.createElement("ul");var D=document.createElement("textarea"),B=document.createElement("button"),F=document.createElement("span"),E=document.createElement("div"),
H=document.createElement("p"),C=document.createElement("button"),G=document.createElement("span");b.className="mainSection section";c.className="lessonTitle";h.className="section contentDivDiv";l.className="leftDiv";q.className="form-control";u.className="form-control";w.className="flex rightDiv";p.className="page1Content";n.className="contenteditableBr form-control";B.className="closeImg close";B.setAttribute("onclick","removeLessonContent(this)");B.setAttribute("type","button");B.setAttribute("aria-label",
"Close");F.setAttribute("aria-hidden","true");F.innerHTML="&times;";E.className="addLessonContent";E.setAttribute("onclick","addLessonContent(this)");C.className="closeImg close";C.setAttribute("onclick","removeLessonContent(this)");C.setAttribute("type","button");C.setAttribute("aria-label","Close");G.setAttribute("aria-hidden","true");G.innerHTML="&times;";f.setAttribute("type","text");f.className="lessonTitleInput form-control";g.setAttribute("type","text");g.className="lessonSubtitleInput form-control";
u.setAttribute("type","color");x.setAttribute("type","text");f.setAttribute("onkeyup","inputToDiv(this)");f.setAttribute("onkeydown","inputToDiv(this)");g.setAttribute("onkeyup","inputToDiv(this)");g.setAttribute("onkeydown","inputToDiv(this)");q.setAttribute("onchange","setActualValue()");u.setAttribute("onchange","setActualValue()");x.setAttribute("onkeyup","inputToDiv(this)");x.setAttribute("onkeydown","inputToDiv(this)");D.setAttribute("onkeyup","inputToDiv(this)");D.setAttribute("onkeydown",
"inputToDiv(this)");e.contentEditable="true";e.className="inputDiv contenteditableBr form-control";e.setAttribute("onkeyup","divToInput(this)");e.setAttribute("onkeydown","divToInput(this)");m.contentEditable="true";m.className="inputDiv contenteditableBr form-control";m.setAttribute("onkeyup","divToInput(this)");m.setAttribute("onkeydown","divToInput(this)");n.contentEditable="true";n.className="inputDiv contenteditableBr form-control";n.setAttribute("onkeyup","divToInput(this)");n.setAttribute("onkeydown",
"divToInput(this)");A.contentEditable="true";A.className="inputDiv form-control";A.setAttribute("onkeyup","divToInput(this)");A.setAttribute("onkeydown","divToInput(this)");$(A).html("<ul><li><br></li></ul>");$(A).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});$(f).css("display","none");$(g).css("display","none");$(x).css("display","none");$(D).css("display","none");d.appendChild(document.createTextNode("Lesson Title"));k.appendChild(document.createTextNode("Subtitle Title"));
c.appendChild(d);c.appendChild(e);c.appendChild(f);c.appendChild(k);c.appendChild(m);c.appendChild(g);d=document.createElement("option");d.appendChild(document.createTextNode("Lecture"));d.setAttribute("value","L");e=document.createElement("option");e.appendChild(document.createTextNode("Practical"));e.setAttribute("value","P");f=document.createElement("option");f.appendChild(document.createTextNode("Tutorial"));f.setAttribute("value","T");k=document.createElement("option");k.appendChild(document.createTextNode("Remark"));
k.setAttribute("value","R");m=document.createElement("option");m.appendChild(document.createTextNode("In Course Assessment"));m.setAttribute("value","ICA");q.appendChild(d);q.appendChild(e);q.appendChild(f);q.appendChild(k);q.appendChild(m);r.appendChild(document.createTextNode("Lecture/Practical/something"));l.appendChild(r);l.appendChild(q);l.appendChild(u);z.appendChild(document.createTextNode("Content Title"));y.appendChild(document.createTextNode("Content List"));p.appendChild(z);p.appendChild(n);
p.appendChild(x);p.appendChild(y);p.appendChild(A);p.appendChild(D);w.appendChild(p);B.appendChild(F);v.appendChild(l);v.appendChild(w);h.appendChild(t);h.appendChild(v);h.appendChild(B);H.appendChild(document.createTextNode("Add new lesson content"));E.appendChild(H);C.appendChild(G);b.appendChild(c);b.appendChild(h);b.appendChild(E);b.appendChild(C);$(a).before(b);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();
makeSortable()}
function recreatePage1(){$("#page1").empty();var a=document.createElement("div"),b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));b.className="bold underline";var c=document.createElement("div");c.contentEditable="true";c.className="inputDiv form-control";c.setAttribute("onkeyup","divToInput(this)");c.setAttribute("onkeydown","divToInput(this)");var d=document.createElement("textarea");d.id="paragraphTextarea";d.setAttribute("onkeyup","inputToDiv(this)");d.setAttribute("onkeydown",
"inputToDiv(this)");$(d).css("display","none");var e=$("#page2 > #lessonPlanTemplate > #instructorsDetails").html().trim().replace(/\t/g,"");$(c).html(e);$(c).keydown(function(a){if(8===a.keyCode&&"<p><br></p>"===$(this).html())return!1});$(d).val(e);a.appendChild(b);a.appendChild(c);a.appendChild(d);$("#page1").append(a);$(".lesson").each(function(){var a=document.createElement("div");a.className="mainSection section";var b=document.createElement("div");b.className="lessonTitle";var d=document.createElement("p");
d.appendChild(document.createTextNode("Lesson Title"));var c=document.createElement("div");c.contentEditable="true";c.className="inputDiv contenteditableBr form-control";c.setAttribute("onkeyup","divToInput(this)");c.setAttribute("onkeydown","divToInput(this)");var e=document.createElement("input");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.className="lessonTitleInput form-control";$(c).html($(this).find(".lessonHeader").children().eq(0).html());
$(e).val($(this).find(".lessonHeader").children().eq(0).html());$(e).css("display","none");var f=document.createElement("p");f.appendChild(document.createTextNode("Lesson Subtitle"));var l=document.createElement("div");l.contentEditable="true";l.className="inputDiv contenteditableBr form-control";l.setAttribute("onkeyup","divToInput(this)");l.setAttribute("onkeydown","divToInput(this)");var r=document.createElement("input");r.setAttribute("onkeyup","inputToDiv(this)");r.setAttribute("onkeydown","inputToDiv(this)");
r.className="lessonSubtitleInput form-control";$(l).html($(this).find(".lessonHeader").children().eq(1).html());$(r).val($(this).find(".lessonHeader").children().eq(1).text());$(r).css("display","none");b.appendChild(d);b.appendChild(c);b.appendChild(e);b.appendChild(f);b.appendChild(l);b.appendChild(r);a.appendChild(b);$(this).find(".lecPracHeader").each(function(){var b=document.createElement("div");b.className="section contentDivDiv";var c=document.createElement("div");c.className="contentDivDivDraggableDiv progress-bar-striped bg-success";
c.style.opacity="0";var d=document.createElement("div");d.className="contentDivDivRight";var e=document.createElement("div");e.className="leftDiv";var f=document.createElement("p");f.appendChild(document.createTextNode("Lecture/Practical/something"));var n=document.createElement("select");n.setAttribute("onchange","setActualValue()");n.className="form-control";var g=document.createElement("option");g.appendChild(document.createTextNode("Lecture"));g.setAttribute("value","L");var h=document.createElement("option");
h.appendChild(document.createTextNode("Practical"));h.setAttribute("value","P");var l=document.createElement("option");l.appendChild(document.createTextNode("Tutorial"));l.setAttribute("value","T");var m=document.createElement("option");m.appendChild(document.createTextNode("Remark"));m.setAttribute("value","R");var k=document.createElement("option");k.appendChild(document.createTextNode("In Course Assessment"));k.setAttribute("value","ICA");n.appendChild(g);n.appendChild(h);n.appendChild(l);n.appendChild(m);
n.appendChild(k);$(n).val($(this).find(".lecPracDiv :first-child").text());g=document.createElement("input");g.setAttribute("onchange","setActualValue()");g.setAttribute("type","color");g.className="form-control";h=$(this).find(".lecPracDiv").css("background-color");$(g).val(rgb2hex(h));e.appendChild(f);e.appendChild(n);e.appendChild(g);f=document.createElement("div");f.className="flex rightDiv";n=document.createElement("div");n.className="page1Content";g=document.createElement("p");g.appendChild(document.createTextNode("Content Title"));
h=document.createElement("div");h.contentEditable="true";h.className="inputDiv contenteditableBr form-control";h.setAttribute("onkeyup","divToInput(this)");h.setAttribute("onkeydown","divToInput(this)");l=document.createElement("input");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this))");l.setAttribute("type","text");$(h).html($(this).find(".lessonPlanContent .lessonPlanContentP").html());$(l).val($(this).find(".lessonPlanContent .lessonPlanContentP").html());
$(l).css("display","none");m=document.createElement("p");m.appendChild(document.createTextNode("Content List"));k=document.createElement("div");k.contentEditable="true";k.className="inputDiv form-control";k.setAttribute("onkeyup","divToInput(this)");k.setAttribute("onkeydown","divToInput(this)");var t=document.createElement("ul"),r=document.createElement("textarea");r.setAttribute("onkeyup","inputToDiv(this)");r.setAttribute("onkeydown","inputToDiv(this)");$(r).css("display","none");var v=$(this).find(".lessonPlanContent ul").html().trim().replace(/\t/g,
"");$(t).html(v);$(k).html(t);$(r).val(v);$(k).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});n.appendChild(g);n.appendChild(h);n.appendChild(l);n.appendChild(m);n.appendChild(k);n.appendChild(r);f.appendChild(n);n=document.createElement("button");n.className="closeImg close";n.setAttribute("onclick","removeLessonContent(this)");n.setAttribute("type","button");n.setAttribute("aria-label","Close");g=document.createElement("span");g.setAttribute("aria-hidden",
"true");g.innerHTML="&times;";n.appendChild(g);d.appendChild(e);d.appendChild(f);b.appendChild(c);b.appendChild(d);b.appendChild(n);a.appendChild(b)});b=document.createElement("div");b.className="addLessonContent";d=document.createElement("img");c=document.createElement("button");c.className="closeImg close";e=document.createElement("span");b.setAttribute("onclick","addLessonContent(this)");d.setAttribute("src","grass2.jpg");d.setAttribute("width","30");d.setAttribute("height","30");c.setAttribute("onclick",
"removeLessonContent(this)");c.setAttribute("type","button");c.setAttribute("aria-label","Close");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";c.appendChild(e);b.appendChild(d);a.appendChild(b);a.appendChild(c);$("#page1").append(a)});a=document.createElement("div");b=document.createElement("img");a.id="addLessonSection";a.className="addLessonContent";a.setAttribute("onclick","addLessonSection(this)");b.setAttribute("src","grass2.jpg");b.setAttribute("width","30");b.setAttribute("height",
"30");a.appendChild(b);b=document.createElement("div");c=document.createElement("p");c.appendChild(document.createTextNode("Footer"));d=document.createElement("div");d.contentEditable="true";d.className="inputDiv contenteditableBr form-control";d.setAttribute("onkeyup","divToInput(this)");d.setAttribute("onkeydown","divToInput(this)");e=document.createElement("input");e.setAttribute("type","text");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.id="lessonPlanFooter";
$(d).html($("#lessonPlanTemplate .sub").html());$(e).val($("#lessonPlanTemplate .sub").html());$(e).css("display","none");b.appendChild(c);b.appendChild(d);b.appendChild(e);c=document.createElement("br");d=document.createElement("button");d.appendChild(document.createTextNode("Generate HTML"));d.setAttribute("onclick","generateHTML()");d.className="btn btn-primary";e=document.createElement("button");e.appendChild(document.createTextNode("Show All"));e.setAttribute("onclick","showAllInput(this)");
e.className="btn";var f=document.getElementById("page1");f.appendChild(a);f.appendChild(b);f.appendChild(c);f.appendChild(d);f.appendChild(e);contentEditableBr();makeSortable()}
function recreatePage2(){$("#page2").empty();var a=document.createElement("div");a.id="lessonPlanTemplate";var b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));var c=document.createElement("div"),d=$("#paragraphTextarea").val();$(c).html(d);b.className="bold underline";c.id="instructorsDetails";a.append(b);a.append(c);$(".mainSection").each(function(){var b=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(d).html($(this).find(".lessonTitleInput").val());
var m=document.createElement("p");$(m).html($(this).find(".lessonSubtitleInput").val());b.className="lesson";c.className="lessonHeader";d.className="bold";m.className="em";c.appendChild(d);c.appendChild(m);b.appendChild(c);$(this).find(".contentDivDiv").each(function(){var a=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(c).css("background-color",$(this).find(".leftDiv input:nth-child(3)").val());$(d).html($(this).find(".leftDiv :nth-child(2)").val());
c.appendChild(d);var e=document.createElement("div"),f=document.createElement("p");$(f).html($(this).find(".rightDiv .page1Content :nth-child(2)").html());var k=$(this).find(".rightDiv .page1Content :nth-child(5)").html();$(e).html(k);a.className="lecPracHeader";c.className="lecPracDiv";d.className="bold";e.className="lessonPlanContent";f.className="lessonPlanContentP";$(e).prepend(f);a.appendChild(c);a.appendChild(e);b.appendChild(a)});a.append(b)});b=document.createElement("p");$(b).html($("#lessonPlanFooter").val());
b.className="sub";a.append(b);$("#page2").append(a)}function setInputValue(){recreatePage1()}function setActualValue(){recreatePage2()}function generateHTML(){$("#popupDiv").modal("show");$("#popup .modal-body textarea").val($("#page2").html().trim())}function closePopup(){$("#popupDiv").modal("hide");$("#popup .generateHTMLRedText").css("display","none")}
function copyToClipboard(){$("#popup .modal-body textarea")[0].select();document.execCommand("copy");$("#popup .generateHTMLRedText").css("display","block")}function copyCommand(){var a=document.createElement("textarea");$(a).text(selectedText);$("#masterDiv").append(a);$(a)[0].select();document.execCommand("copy");$(a).remove()}function promptLink(){0<selectedText.length&&($("#linkInput").val(""),$("#linkBoxDiv").modal("show"))}
function hideLinkBox(){$("#linkBoxDiv").modal("hide");changeInputBoxSelection(1)}
function changeInputBoxSelection(a){$(".dropdown-menu > .active.dropdown-item")[0].classList.remove("active");var b=$("#linkBoxOptions"),c=$("#linkInput");switch(a){case 1:b.text("Webpage");c[0].setAttribute("placeholder","https://");c.val("");$(".dropdown-menu > a:first-child")[0].classList.add("active");break;case 2:b.text("Email");c[0].setAttribute("placeholder","example@nyp.edu.sg");/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&c.val(htmlEncode(selectedText));
$(".dropdown-menu > a:nth-child(2)")[0].classList.add("active");break;case 3:b.text("Javascript"),c[0].setAttribute("placeholder","alert('Hello')"),c.val(""),$(".dropdown-menu > a:nth-child(4)")[0].classList.add("active")}}
function checkAndDisplayAlert(){var a=document.createElement("div");a.className="alert alert-warning fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var b=document.createElement("p"),c=document.createElement("div"),d=document.createElement("button");d.className="close";d.setAttribute("type","button");d.setAttribute("data-dismiss","alert");d.setAttribute("aria-label","Close");var e=document.createElement("span");d.setAttribute("aria-hidden","true");d.innerHTML="&times;";d.appendChild(e);
c.appendChild(d);a.appendChild(b);a.appendChild(c);c=$("#linkInput").val();d=$("#linkBoxOptions").text();"Webpage"===d?/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(c)?closeAlert():(closeAlert(),b.appendChild(document.createTextNode("The URL entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):"Email"===d&&(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(c)?
closeAlert():(closeAlert(),b.appendChild(document.createTextNode("The email entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)))}function whichLinkSelection(){var a=$("#linkBoxOptions").text();if("Webpage"===a)return"";if("Email"===a)return"mailto:";if("Javascript"===a)return"javascript:";alert("Unexpected error");return null}
function convertToLink(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var b=document.createElement("p"),c=document.createElement("div"),d=document.createElement("button");d.className="close";d.setAttribute("type","button");d.setAttribute("data-dismiss","alert");d.setAttribute("aria-label","Close");var e=document.createElement("span");d.setAttribute("aria-hidden","true");d.innerHTML="&times;";d.appendChild(e);
c.appendChild(d);a.appendChild(b);a.appendChild(c);if(c=$("#linkInput").val()){if(""===whichLinkSelection()){if(!/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(c)&&!confirm("The URL entered does not match the format. Do you want to continue?"))return b.appendChild(document.createTextNode("The URL entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1}else if("mailto:"===
whichLinkSelection()&&!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&!confirm("The email entered does not match the format. Do you want to continue?"))return b.appendChild(document.createTextNode("The email entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1;d=htmlEncode(selectedText);
var f=focusedInput;e=f.html();c=whichLinkSelection()?"<a href='"+whichLinkSelection()+$("#linkInput").val()+"' target='_blank'>"+d+"</a>":"<a href='"+$("#linkInput").val()+"' target='_blank'>"+d+"</a>";startIndex=f.next().val().indexOf(d);var k=escape("<a href="),m=escape("</a>");(new RegExp("("+k+").*("+escape(d)+").*("+m+")")).test(escape(f.next().val()))?(b.appendChild(document.createTextNode("Error! You already made this a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):-1!==
startIndex?(a=e.substring(0,startIndex),b=e.substring(startIndex+d.length),a=a+c+b,focusedInput.next().val(a),focusedInput.html(focusedInput.next().val()),setActualValue()):(b.appendChild(document.createTextNode("Error! Make sure the text selected is not overlapping with another link.")),$("#linkBox > .modal-content > .modal-body").prepend(a));hideLinkBox()}else b.appendChild(document.createTextNode("Please enter a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)}
function divToInput(a){$(a).next().val(a.innerHTML);setActualValue()}function inputToDiv(a){$(a).prev().html(a.value);setActualValue()}var notClicked=!0;function showAllInput(a){notClicked?($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"),a.innerHTML="Hide All",notClicked=!1):($(".inputDiv").next().css("display","none"),$("textarea:not(#popup > textarea)").css("display","none"),a.innerHTML="Show All",notClicked=!0)}
function checkEnterKey(a){if(13===a.keyCode)return document.execCommand("insertHTML",!1,"<br /><br />"),!1}function contentEditableBr(){$(document).off("keydown",".contenteditableBr",checkEnterKey);$(document).on("keydown",".contenteditableBr",checkEnterKey)}function selectAll(a){a.setSelectionRange(0,a.value.length)}
$(function(){$(".carousel-control-prev").css("display","none");clearImportTextarea();$(window.document).on("focusout","#linkInput",checkAndDisplayAlert);if($(".inputDiv").addEventListener)$(".inputDiv").addEventListener("contextmenu",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var b=window.getSelection();b.rangeCount&&(startIndex=b.focusOffset)}else"undefined"!=typeof document.selection&&"Text"==window.document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?
selectedText=window.getSelection().toString():window.document.selection&&"Control"!=window.document.selection.type&&(selectedText=window.document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),a.preventDefault())},!1);else $("body").on("contextmenu",".inputDiv",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var b=window.getSelection();b.rangeCount&&(startIndex=b.focusOffset)}else"undefined"!=
typeof document.selection&&"Text"==document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?selectedText=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(selectedText=document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),window.event.returnValue=!1)});$(document).bind("click",function(a){$("#rightClickMenu").css("display","none")});$(document).on("mouseover",
".contentDivDivDraggableDiv",function(){$(this).stop(!0,!0);$(this).animate({opacity:1,queue:!1},300)});$(document).on("mouseout",".contentDivDivDraggableDiv",function(){$(this).animate({opacity:0},300)});contentEditableBr()});var hexDigits="0123456789abcdef".split("");function rgb2hex(a){return(a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/))?"#"+hex(a[1])+hex(a[2])+hex(a[3]):"#000000"}function hex(a){return isNaN(a)?"00":hexDigits[(a-a%16)/16]+hexDigits[a%16]}
function htmlEncode(a){return $("<div/>").text(a).html()}function htmlDecode(a){return a.replace(/&#(\d+);?/g,function(a,c){return String.fromCharCode(c)})};
