var selectedText="",focusedInput,startIndex,shouldGoBackHide=0,notClicked=!0,file,colourTemplate='{\n   "Lecture": "#b0c4de",\n   "Practical": "#b0c4de",\n   "Tutorial": "#b0c4de",\n   "Remark": "#81c784",\n   "E-Learning": "#81c784",\n   "In Course Assessment": "#FA8072"\n}',selectOptions="{'Lecture','Practical','Tutorial','Remark','E-Learning','In Course Assessment'}";
$(function(){$(".carousel-control-prev").css("display","none");clearImportTextarea();$(window.document).on("focusout","#linkInput",checkAndDisplayAlert);if($(".inputDiv").addEventListener)$(".inputDiv").addEventListener("contextmenu",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var c=window.getSelection();c.rangeCount&&(startIndex=c.focusOffset)}else"undefined"!=typeof document.selection&&"Text"==window.document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?
selectedText=window.getSelection().toString():window.document.selection&&"Control"!=window.document.selection.type&&(selectedText=window.document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),a.preventDefault())},!1);else $(document).on("contextmenu",".inputDiv",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var c=window.getSelection();c.rangeCount&&(startIndex=c.focusOffset)}else"undefined"!=
typeof document.selection&&"Text"==document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?selectedText=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(selectedText=document.selection.createRange().text);if(selectedText)return $("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),(a||window.event).returnValue=!1});$(document).bind("click",function(a){$("#rightClickMenu").css("display","none")});
$(document).on("mouseover",".contentDivDivDraggableDiv",function(){$(this).stop(!0,!0);$(this).animate({opacity:1,queue:!1},300)});$(document).on("mouseout",".contentDivDivDraggableDiv",function(){$(this).animate({opacity:0},300)});$(document).on("change","#excelSelectInput",function(){$(this).hasClass("is-invalid")&&($(this).removeClass("is-invalid"),$(this).addClass("is-valid"))});$(document).on("change",".remapExcelSelectInput",function(){$(this).hasClass("is-invalid")&&($(this).removeClass("is-invalid"),
$(this).addClass("is-valid"))});contentEditableBr();$(document).on("click","#instructionPage,#instructionPageCloseBtn",function(){localStorage.setItem("instructionViewed",!0);localStorage.setItem("instructionViewedTime",(new Date).getTime());$("#instructionPage").fadeOut("slow");document.body.style.overflow="auto"});$(document).on("click","#instructionPageModal",function(a){a.stopPropagation()});document.body.style.cursor="auto"});
function goPage2(){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++}function goPage3(a){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++;$("#importPage3Preview").empty();$("#importPage3Preview").append(a)}
function goBack(){closeAlert();$("#carousel").carousel("prev");$("#carousel").carousel("pause");shouldGoBackHide--;0>=shouldGoBackHide&&$(".carousel-control-prev").css("display","none")}
function createNew(){$("#startupDiv").fadeOut();$("#masterDiv").css("overflow","auto");localStorage.instructionViewed?localStorage.instructionViewedTime&&6048E4<(new Date).getTime()-localStorage.instructionViewedTime&&(localStorage.removeItem("instructionViewed"),localStorage.removeItem("instructionViewedTime"),document.body.style.overflow="hidden",$("#instructionPageContent").children().first().css("display","block"),getInstructionGif(0),$("#instructionPage").fadeIn("slow")):(document.body.style.overflow=
"hidden",$("#instructionPageContent").children().first().css("display","block"),getInstructionGif(0),$("#instructionPage").fadeIn("slow"));$("#masterDiv").css("height","unset");$("#page1").empty();recreatePage1()}function closeAlert(){$(".alert").alert("close")}
function checkTextIsCorrect(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="page2Error";a.setAttribute("role","alert");var c=document.createElement("p"),d=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML="&times;";b.appendChild(e);
d.appendChild(b);a.appendChild(c);a.appendChild(d);(d=$("#importTextarea").val().trim())?(b=$(document.createElement("div")),b.html(d),(d=b.find("#lessonPlanTemplate").html())?(d=d.trim(),0<d.length?(c=document.createElement("div"),c.id="lessonPlanTemplate",$(c).html(d),goPage3(c)):(c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):
(c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):(c.appendChild(document.createTextNode("Make sure you entered/uploaded something")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))}
function fileMatchesLayout(a){closeAlert();var c=document.createElement("div");c.className="alert alert-danger fade show";c.id="page2Error";c.setAttribute("role","alert");var d=document.createElement("p"),b=document.createElement("div"),e=document.createElement("button");e.className="close";e.setAttribute("type","button");e.setAttribute("data-dismiss","alert");e.setAttribute("aria-label","Close");var f=document.createElement("span");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";e.appendChild(f);
b.appendChild(e);c.appendChild(d);c.appendChild(b);if(a=a.trim())if(b=$(document.createElement("div")),b.html(a),a=b.find("#lessonPlanTemplate").html()){a=a.trim();if(0<a.length)return!0;d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly"))}else d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly"));else d.appendChild(document.createTextNode("Make sure you entered/uploaded something"));
$("#startupDivPage2 > div").prepend(c);$("#page2Error").slideDown(function(){c.style.display="flex"});return!1}function hideStartupDiv(){$("#page2").empty();$("#page2").html($("#importPage3Preview").html());$("#importPage3Preview").empty();createNew()}
function allowDrop(a){window.File&&window.FileReader&&window.FileList&&window.Blob?($("#importTextarea").css("border","5px dashed grey"),$("#importTextarea").css("border-radius","20px"),a.preventDefault()):alert("Browser doesn't support drag and drop")}function removeDragCSS(){$("#importTextarea").css("border","");$("#importTextarea").css("border-radius","")}
function drop(a){a.preventDefault();removeDragCSS();$(".progress-bar").css("width","0%");$(".progress-bar")[0].classList.add("progress-bar-animated");$("#remappingDiv").collapse("hide");$("#remapIcon")[0].classList.add("fa-plus-square");$("#remapIcon")[0].classList.remove("fa-minus-square");a=a.dataTransfer?a.dataTransfer.files:a.target.files;if(!a[0])return!1;file=a[0];var c=new FileReader;file.type.match("text/plain")||file.type.match("text/html")?(c.onload=function(){var a=c.result;fileMatchesLayout(a)&&
($("#uploadedFileName").html(file.name),$("#importTextarea").val(a))},c.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"),console.log(a))},c.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")}):file.type.match("application/vnd.ms-excel")||file.type.match("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")?(showColumn(file),$("#excelBoxDiv").modal("show")):alert("Only .html, .txt & .xls(x) is the accepted file format");
c.readAsText(file)}
function showColumn(a){var c=new FileReader;c.onload=function(a){var b="";a=new Uint8Array(a.target.result);for(var c=a.byteLength,d=0;d<c;d++)b+=String.fromCharCode(a[d]);b=XLSX.read(b,{type:"binary",cellDates:!0,cellStyles:!0});$("#excelSelectInput").empty();$("#excelSelectInput2").empty();a=$("<option disabled selected>Please select your primary column</option>");$("#excelSelectInput").append(a);a=$("<option selected>Please select your secondary column</option>");$("#excelSelectInput2").append(a);b=
b.Sheets[b.SheetNames[0]];a=XLSX.utils.decode_range(b["!ref"]);$("#remappingDiv > .card-body").empty();for(c=a.s.c;c<=a.e.c;c++)if(d=XLSX.utils.encode_cell({c:c,r:0}),b[d]){var g=String(b[d].v);d=document.createElement("option");d.appendChild(document.createTextNode(g));d.value=c;var k=document.createElement("option");k.appendChild(document.createTextNode(g));k.value=c;$("#excelSelectInput").append(d);$("#excelSelectInput2").append(k);d=document.createElement("div");d.className="form-group";k=document.createElement("p");
k.appendChild(document.createTextNode("Table Header: "));k.className="remapColumnHeader";var A=document.createElement("p");A.appendChild(document.createTextNode(g));g=document.createElement("p");g.appendChild(document.createTextNode("Map to: "));g.className="remapColumnHeader";var t=document.createElement("select");t.className="custom-select remapExcelSelectInput";t.style.marginBottom="8px";var q=document.createElement("option");q.appendChild(document.createTextNode("Select an option"));q.selected=
!0;var p=document.createElement("option");p.appendChild(document.createTextNode("Lecture"));p.setAttribute("value","0");var l=document.createElement("option");l.appendChild(document.createTextNode("Practical"));l.setAttribute("value","1");var m=document.createElement("option");m.appendChild(document.createTextNode("Tutorial"));m.setAttribute("value","2");var n=document.createElement("option");n.appendChild(document.createTextNode("Remark"));n.setAttribute("value","3");var h=document.createElement("option");
h.appendChild(document.createTextNode("E-Learning"));h.setAttribute("value","4");var r=document.createElement("option");r.appendChild(document.createTextNode("In Course Assessment"));r.setAttribute("value","5");t.appendChild(q);t.appendChild(p);t.appendChild(l);t.appendChild(m);t.appendChild(n);t.appendChild(h);t.appendChild(r);d.appendChild(k);d.appendChild(A);d.appendChild(g);d.appendChild(t);$("#remappingDiv > .card-body").append(d)}};c.readAsArrayBuffer(a)}
function excelMoveToPage(a){switch(a){case 1:$("#excelPage1").fadeIn();$("#excelPage2").fadeOut();break;case 2:$("#excelSelectInput").val()&&0<=$("#excelSelectInput").val()?($("#excelPage3")[0].style.left="5%",$("#excelPage3")[0].style.top="10%",$("#excelPage3").css("position","absolute"),$("#excelPage1").fadeOut(),$("#excelPage2").fadeIn(),$("#excelPage3").fadeOut(),$(".modal-footer > button:nth-child(2)").css("display","none")):$("#excelSelectInput").addClass("is-invalid");$("#excelPage3 > .excelPopupButtonDiv > button").css("position",
"block");break;case 3:$("#excelPage2").fadeOut();$("#excelPage3").fadeIn(function(){$("#excelPage3")[0].style.left=0;$("#excelPage3")[0].style.top=0;$("#excelPage3").css("position","relative")});$(".modal-footer > button:nth-child(2)").css("display","block");break;default:alert("What? How is this possible... Stop it")}}
function startProcessingExcel(){var a;if($("#excelSelectInput").val()&&0<=$("#excelSelectInput").val()){var c=document.getElementById("customControlAutosizing").checked,d=document.createElement("div");d.id="lessonPlanTemplate";var b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));var e=document.createElement("div");b.className="bold underline";e.id="instructorsDetails";d.append(b);d.append(e);var f=$("#excelSelectInput").val(),g=$("#excelSelectInput2").val();
0<=f&&($("#uploadedFileName").html(file.name),b=new FileReader,b.onload=function(b){var e="";b=new Uint8Array(b.target.result);for(var k=b.byteLength,q=0;q<k;q++)e+=String.fromCharCode(b[q]);e=XLSX.read(e,{type:"binary",cellDates:!0,cellStyles:!0});e=e.Sheets[e.SheetNames[0]];b=a=XLSX.utils.decode_range(e["!ref"]);k={lecture:[],practical:[],tutorial:[],remark:[],eLearning:[],iCA:[]};k=getRemapFromInput(k,f,g);q=[];for(var p=b.s.c;p<=b.e.c;p++){var l=!1;for(keyValue in k)if(k.hasOwnProperty(keyValue))for(i=
0;i<k[keyValue].length;i++)if(parseInt(k[keyValue][i])===p){l=!0;break}l||(l=XLSX.utils.encode_cell({c:p,r:0}),e[l]&&(l=String(e[l].v).toLowerCase(),-1!==l.indexOf("lecture")?k.lecture.push(p):-1!==l.indexOf("practical")?k.practical.push(p):-1!==l.indexOf("tutorial")?k.tutorial.push(p):-1!==l.indexOf("remark")?k.remark.push(p):-1!==l.indexOf("e-learning")||-1!==l.indexOf("elearning")?k.eLearning.push(p):-1!==l.indexOf("ica")||-1!==l.indexOf("in course assessment")?k.iCA.push(p):p!==parseInt(f)&&p!==
parseInt(g)&&q.push(p)))}if(0<q.length){p="Some columns could not be mapped automatically. Do you want to continue without mapping the Column(s): ";l=!0;for(var m=0;m<q.length;m++){var n=XLSX.utils.encode_cell({c:q[m],r:0});e[n]&&(n=String(e[n].v),$("#remappingDiv > .card-body").children().eq(q[m]).find("select").addClass("is-invalid"),l?(p+=n,l=!1):p=m===q.length-1?p+(" & "+n+"?"):p+(", "+n))}if(!confirm(p))return!1}for(q=b.s.r+1;q<=b.e.r;q++)if(p=XLSX.utils.encode_cell({c:f,r:q}),e[p]){var h=e[p],
r=String(h.v);p=document.createElement("div");l=document.createElement("div");m=document.createElement("p");n=document.createElement("p");p.className="lesson";l.className="lessonHeader";m.className="bold";n.className="em";h.l?isNaN(h.v)?$(m).html("<a href='"+h.l.Target+"' target='_blank'>"+h.v+"</a>"):$(m).html("<a href='"+h.l.Target+"' target='_blank'>Week "+h.v+"</a>"):isNaN(h.v)?$(m).html(r):$(m).html("Week "+r);g&&0<=g&&(h=checkIfMerged(e,g,q),h=h.found?XLSX.utils.encode_cell({c:h.sC,r:h.sR}):
XLSX.utils.encode_cell({c:g,r:q}),e[h]&&(h=e[h],r=String(h.v),h.l?isNaN(h.v)?$(n).html("<a href='"+h.l.Target+"' target='_blank'>"+h.v+"</a>"):$(n).html("<a href='"+h.l.Target+"' target='_blank'>Week "+h.v+"</a>"):isNaN(h.v)?$(n).html(r):$(n).html("Week "+r)));l.appendChild(m);l.appendChild(n);p.appendChild(l);l=checkIfMerged(e,f,q);if("row"===l.direction)for(l=l.eR-l.sR,m=b.s.c;m<=b.e.c;m++){if(n=null,m!=f&&m!=g){for(h=q;h<=q+l;h++)if(!(h>q&&"row"===checkIfMerged(e,m,q).direction)){r=checkIfMerged(e,
m,h);var u="column"===r.direction||"both"===r.direction?XLSX.utils.encode_cell({c:r.sC,r:r.sR}):XLSX.utils.encode_cell({c:m,r:h});if(e[u]){var w=getHeader(k,m);r=w.header;var v=w.lecPrac,y=document.createElement("div"),z=document.createElement("p");w=document.createElement("ul");y.className="lessonPlanContent";z.className="lessonPlanContentP";var x=e[u];u=String(x.v).trim().split("\n");var B="";if(x.l){u=x.v.trim().split("\n");for(var C=0;C<u.length;C++)B+="<li><a href='"+x.l.Target+"' target='_blank'>"+
u[C]+"</a></li>"}else for(x=0;x<u.length;x++)B+="<li>"+u[x]+"</li>";$(w).html(B);y.appendChild(z);y.appendChild(w);r.appendChild(v);r.appendChild(y);p.appendChild(r);c&&(n?h>q&&("row"===checkIfMerged(e,m,q).direction||"both"===checkIfMerged(e,m,q).direction)||(v=n.find(".lessonPlanContent > ul"),w=v.html()+w.innerHTML,$(v).html(w),$(r).remove()):n=$(r))}}d.appendChild(p)}}else{for(l=b.s.c;l<=b.e.c;l++)if(l!=f&&l!=g&&(m=checkIfMerged(e,l,q),v="column"===m.direction||"both"===m.direction||"row"===m.direction?
XLSX.utils.encode_cell({c:m.sC,r:m.sR}):XLSX.utils.encode_cell({c:l,r:q}),e[v])){n=getHeader(k,l);m=n.header;n=n.lecPrac;h=document.createElement("div");r=document.createElement("p");w=document.createElement("ul");h.className="lessonPlanContent";r.className="lessonPlanContentP";z=e[v];v=String(z.v).trim().split("\n");y="";if(z.l)for(v=z.v.trim().split("\n"),u=0;u<v.length;u++)y+="<li><a href='"+z.l.Target+"' target='_blank'>"+v[u]+"</a></li>";else for(z=0;z<v.length;z++)y+="<li>"+v[z]+"</li>";$(w).html(y);
h.appendChild(r);h.appendChild(w);m.appendChild(n);m.appendChild(h);p.appendChild(m)}d.appendChild(p)}}$("#importTextarea").val(d.outerHTML);$("#excelBoxDiv").modal("hide");$("#excelSelectInput").removeClass("is-valid");excelMoveToPage(2);excelMoveToPage(1)},b.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"))},b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")},b.readAsArrayBuffer(file))}else $("#excelSelectInput").addClass("is-invalid")}
function getHeader(a,c){var d=document.createElement("div"),b=document.createElement("div"),e=document.createElement("p");b.appendChild(e);d.className="lecPracHeader";b.className="lecPracDiv";e.className="bold";var f=checkIfColumnsHeader(a,c);f?($(e).html(f),e=JSON.parse(colourTemplate),e[f]&&(b.style.background=e[f])):($(e).html("Lecture"),f=JSON.parse(colourTemplate),f.Lecture&&(b.style.background=f.Lecture));return{header:d,lecPrac:b}}
function checkIfColumnsHeader(a,c){var d=null,b;for(b in a)if(a.hasOwnProperty(b))for(i=0;i<a[b].length;i++)if(parseInt(a[b][i])===c)if("lecture"===b){d="Lecture";break}else if("practical"===b){d="Practical";break}else if("tutorial"===b){d="Tutorial";break}else if("remark"===b){d="Remark";break}else if("eLearning"===b){d="E-Learning";break}else if("iCA"===b){d="In Course Assessment";break}return d}
function getRemapFromInput(a,c,d){$("#remappingDiv > .card-body").children().each(function(b){if(b===c||b===d)return!1;switch(parseInt($(this).find("select").val())){case 0:a.lecture.push(b);break;case 1:a.practical.push(b);break;case 2:a.tutorial.push(b);break;case 3:a.remark.push(b);break;case 4:a.eLearning.push(b);break;case 5:a.iCA.push(b)}});return a}
function disableRemap(){$("#remappingDiv > .card-body").children().each(function(){var a=$(this).find("select");a[0].hasAttribute("disabled")&&a.removeAttr("disabled")});if($("#excelSelectInput").val()){var a=$("#remappingDiv > .card-body").children().eq($("#excelSelectInput").val()).find("select");a.attr("disabled","disabled");a[0].selectedIndex="0"}0!==$("#excelSelectInput2")[0].selectedIndex&&(a=$("#remappingDiv > .card-body").children().eq($("#excelSelectInput2").val()).find("select"),a.attr("disabled",
"disabled"),a[0].selectedIndex="0")}function changeRemapIcon(){$("#remapIcon").hasClass("fa-plus-square")?($("#remapIcon")[0].classList.add("fa-minus-square"),$("#remapIcon")[0].classList.remove("fa-plus-square")):($("#remapIcon")[0].classList.add("fa-plus-square"),$("#remapIcon")[0].classList.remove("fa-minus-square"))}
function checkIfMerged(a,c,d){if(a=a["!merges"]){a=Object.values(a);for(var b=0;b<a.length;b++){var e=a[b].s.c,f=a[b].e.c,g=a[b].s.r,k=a[b].e.r;if(c>=e&&c<=f&&d>=g&&d<=k){if(f>e)return k>g?{found:!0,sC:e,eC:f,sR:g,eR:k,direction:"both"}:{found:!0,sC:e,eC:f,sR:g,eR:k,direction:"column"};if(k>g)return{found:!0,sC:e,eC:f,sR:g,eR:k,direction:"row"}}}}return{found:!1,sC:null,eC:null,sR:null,eR:null,direction:"none"}}
function clearImportTextarea(){$("#inputGroupFile01").val(null);$("#uploadedFileName").html("Choose file");$("#importTextarea").val("");$(".progress-bar").css("width","0%")}
function makeSortable(){$(".mainSection").sortable({connectWith:".mainSection",items:".contentDivDiv",handle:".contentDivDivDraggableDiv",cancel:".inputDiv, textarea, input, button",update:function(){setActualValue()},axis:"y",cursor:"move",opacity:.5});$("#page1").sortable({items:".mainSection",cancel:":not('.draggableDiv')"})}function removeLessonContent(a){$(a).parent().fadeOut("swing",function(){$(a).parent().remove();recreatePage2()})}
function addLessonContent(a){var c=document.createElement("div"),d=document.createElement("div");d.className="contentDivDivDraggableDiv progress-bar-striped bg-success";d.style.opacity="0";var b=document.createElement("div");b.className="contentDivDivRight";var e=document.createElement("div"),f=document.createElement("p"),g=document.createElement("select"),k=document.createElement("input"),A=document.createElement("div"),t=document.createElement("div"),q=document.createElement("p"),p=document.createElement("div"),
l=document.createElement("input"),m=document.createElement("p"),n=document.createElement("div"),h=document.createElement("textarea"),r=document.createElement("button"),u=document.createElement("span");c.className="section contentDivDiv";e.className="leftDiv";g.className="inputDiv custom-select";k.className="form-control";A.className="flex rightDiv";t.className="page1Content";r.className="closeImg close";r.setAttribute("onclick","removeLessonContent(this)");r.setAttribute("type","button");r.setAttribute("aria-label",
"Close");u.setAttribute("aria-hidden","true");u.innerHTML="&times;";k.setAttribute("type","color");l.setAttribute("type","text");g.setAttribute("onchange","setActualColour(this)");k.setAttribute("onchange","setActualValue()");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this)");h.setAttribute("onkeyup","inputToDiv(this)");h.setAttribute("onkeydown","inputToDiv(this)");p.contentEditable="true";p.className="inputDiv contenteditableBr form-control";p.setAttribute("onkeyup",
"divToInput(this)");p.setAttribute("onkeydown","divToInput(this)");n.contentEditable="true";n.className="inputDiv form-control";n.setAttribute("onkeyup","divToInput(this)");n.setAttribute("onkeydown","divToInput(this)");$(n).html("<ul><li><br></li></ul>");$(n).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});var w=JSON.parse(colourTemplate);$(k).css("display","none");k.value=w.Lecture;$(l).css("display","none");$(h).css("display","none");$(h).text("<ul><li>>br></li></ul>");
w=document.createElement("option");w.appendChild(document.createTextNode("Lecture"));w.setAttribute("value","Lecture");var v=document.createElement("option");v.appendChild(document.createTextNode("Practical"));v.setAttribute("value","Practical");var y=document.createElement("option");y.appendChild(document.createTextNode("Tutorial"));y.setAttribute("value","Tutorial");var z=document.createElement("option");z.appendChild(document.createTextNode("Remark"));z.setAttribute("value","Remark");var x=document.createElement("option");
x.appendChild(document.createTextNode("E-Learning"));x.setAttribute("value","E-Learning");var B=document.createElement("option");B.appendChild(document.createTextNode("In Course Assessment"));B.setAttribute("value","In Course Assessment");g.appendChild(w);g.appendChild(v);g.appendChild(y);g.appendChild(z);g.appendChild(x);g.appendChild(B);f.appendChild(document.createTextNode("Lesson/ICA Type"));e.appendChild(f);e.appendChild(g);e.appendChild(k);q.appendChild(document.createTextNode("Title"));m.appendChild(document.createTextNode("Topics"));
t.appendChild(q);t.appendChild(p);t.appendChild(l);t.appendChild(m);t.appendChild(n);t.appendChild(h);A.appendChild(t);r.appendChild(u);b.appendChild(e);b.appendChild(A);c.appendChild(d);c.appendChild(b);c.appendChild(r);$(a).before(c);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function addLessonSection(a){var c=document.createElement("div"),d=document.createElement("div"),b=document.createElement("p"),e=document.createElement("div"),f=document.createElement("input"),g=document.createElement("p"),k=document.createElement("div"),A=document.createElement("input"),t=document.createElement("div"),q=document.createElement("div");q.className="contentDivDivDraggableDiv progress-bar-striped bg-success";q.style.opacity="0";var p=document.createElement("div");p.className="contentDivDivRight";
var l=document.createElement("div"),m=document.createElement("p"),n=document.createElement("select"),h=document.createElement("input"),r=document.createElement("div"),u=document.createElement("div"),w=document.createElement("p"),v=document.createElement("div"),y=document.createElement("input"),z=document.createElement("p"),x=document.createElement("div");document.createElement("ul");var B=document.createElement("textarea"),C=document.createElement("button"),F=document.createElement("span"),E=document.createElement("div"),
H=document.createElement("i"),I=document.createElement("p"),D=document.createElement("button"),G=document.createElement("span");c.className="mainSection section";d.className="lessonTitle";t.className="section contentDivDiv";l.className="leftDiv";n.className="inputDiv custom-select";h.className="form-control";r.className="flex rightDiv";u.className="page1Content";v.className="contenteditableBr form-control";C.className="closeImg close";C.setAttribute("onclick","removeLessonContent(this)");C.setAttribute("type",
"button");C.setAttribute("aria-label","Close");F.setAttribute("aria-hidden","true");F.innerHTML="&times;";I.appendChild(document.createTextNode("Add New Lesson/ICA"));H.className="fas fa-plus-circle";E.className="addLessonContent";E.setAttribute("onclick","addLessonContent(this)");D.className="closeImg close";D.setAttribute("onclick","removeLessonContent(this)");D.setAttribute("type","button");D.setAttribute("aria-label","Close");G.setAttribute("aria-hidden","true");G.innerHTML="&times;";f.setAttribute("type",
"text");f.className="lessonTitleInput form-control";A.setAttribute("type","text");A.className="lessonSubtitleInput form-control";h.setAttribute("type","color");y.setAttribute("type","text");f.setAttribute("onkeyup","inputToDiv(this)");f.setAttribute("onkeydown","inputToDiv(this)");A.setAttribute("onkeyup","inputToDiv(this)");A.setAttribute("onkeydown","inputToDiv(this)");n.setAttribute("onchange","setActualColour(this)");h.setAttribute("onchange","setActualValue()");y.setAttribute("onkeyup","inputToDiv(this)");
y.setAttribute("onkeydown","inputToDiv(this)");B.setAttribute("onkeyup","inputToDiv(this)");B.setAttribute("onkeydown","inputToDiv(this)");e.contentEditable="true";e.className="inputDiv contenteditableBr form-control";e.setAttribute("onkeyup","divToInput(this)");e.setAttribute("onkeydown","divToInput(this)");k.contentEditable="true";k.className="inputDiv contenteditableBr form-control";k.setAttribute("onkeyup","divToInput(this)");k.setAttribute("onkeydown","divToInput(this)");v.contentEditable="true";
v.className="inputDiv contenteditableBr form-control";v.setAttribute("onkeyup","divToInput(this)");v.setAttribute("onkeydown","divToInput(this)");x.contentEditable="true";x.className="inputDiv form-control";x.setAttribute("onkeyup","divToInput(this)");x.setAttribute("onkeydown","divToInput(this)");$(x).html("<ul><li><br></li></ul>");$(x).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});var J=JSON.parse(colourTemplate);$(f).css("display","none");$(A).css("display",
"none");$(h).css("display","none");h.value=J.Lecture;$(y).css("display","none");$(B).css("display","none");b.appendChild(document.createTextNode("Lesson Title"));g.appendChild(document.createTextNode("Subtitle Title"));d.appendChild(b);d.appendChild(e);d.appendChild(f);d.appendChild(g);d.appendChild(k);d.appendChild(A);b=document.createElement("option");b.appendChild(document.createTextNode("Lecture"));b.setAttribute("value","Lecture");e=document.createElement("option");e.appendChild(document.createTextNode("Practical"));
e.setAttribute("value","Practical");f=document.createElement("option");f.appendChild(document.createTextNode("Tutorial"));f.setAttribute("value","Tutorial");g=document.createElement("option");g.appendChild(document.createTextNode("Remark"));g.setAttribute("value","Remark");k=document.createElement("option");k.appendChild(document.createTextNode("E-Learning"));k.setAttribute("value","E-Learning");A=document.createElement("option");A.appendChild(document.createTextNode("In Course Assessment"));A.setAttribute("value",
"In Course Assessment");n.appendChild(b);n.appendChild(e);n.appendChild(f);n.appendChild(g);n.appendChild(k);n.appendChild(A);m.appendChild(document.createTextNode("Lesson/ICA Type"));l.appendChild(m);l.appendChild(n);l.appendChild(h);w.appendChild(document.createTextNode("Title"));z.appendChild(document.createTextNode("Topics"));u.appendChild(w);u.appendChild(v);u.appendChild(y);u.appendChild(z);u.appendChild(x);u.appendChild(B);r.appendChild(u);C.appendChild(F);p.appendChild(l);p.appendChild(r);
t.appendChild(q);t.appendChild(p);t.appendChild(C);E.appendChild(H);E.appendChild(I);D.appendChild(G);c.appendChild(d);c.appendChild(t);c.appendChild(E);c.appendChild(D);$(a).before(c);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function recreatePage1(){$("#page1").empty();var a=document.createElement("div"),c=document.createElement("p");c.appendChild(document.createTextNode("Instructors Details"));c.className="bold underline";var d=document.createElement("div");d.contentEditable="true";d.className="inputDiv form-control";d.setAttribute("onkeyup","divToInput(this)");d.setAttribute("onkeydown","divToInput(this)");var b=document.createElement("textarea");b.id="paragraphTextarea";b.setAttribute("onkeyup","inputToDiv(this)");
b.setAttribute("onkeydown","inputToDiv(this)");$(b).css("display","none");var e=$("#page2 > #lessonPlanTemplate > #instructorsDetails").html().trim().replace(/\t/g,"");$(d).html(e);$(d).keydown(function(a){if(8===a.keyCode&&"<p><br></p>"===$(this).html())return!1});$(b).val(e);a.appendChild(c);a.appendChild(d);a.appendChild(b);$("#page1").append(a);$(".lesson").each(function(){var a=document.createElement("div");a.className="mainSection section";var b=document.createElement("div");b.className="lessonTitle";
var c=document.createElement("p");c.appendChild(document.createTextNode("Lesson Title"));var d=document.createElement("div");d.contentEditable="true";d.className="inputDiv contenteditableBr form-control";d.setAttribute("onkeyup","divToInput(this)");d.setAttribute("onkeydown","divToInput(this)");var e=document.createElement("input");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.className="lessonTitleInput form-control";$(d).html($(this).find(".lessonHeader").children().eq(0).html());
$(e).val($(this).find(".lessonHeader").children().eq(0).html());$(e).css("display","none");var l=document.createElement("p");l.appendChild(document.createTextNode("Lesson Subtitle"));var f=document.createElement("div");f.contentEditable="true";f.className="inputDiv contenteditableBr form-control";f.setAttribute("onkeyup","divToInput(this)");f.setAttribute("onkeydown","divToInput(this)");var g=document.createElement("input");g.setAttribute("onkeyup","inputToDiv(this)");g.setAttribute("onkeydown","inputToDiv(this)");
g.className="lessonSubtitleInput form-control";$(f).html($(this).find(".lessonHeader").children().eq(1).html());$(g).val($(this).find(".lessonHeader").children().eq(1).text());$(g).css("display","none");var h=document.createElement("input");h.setAttribute("onchange","setActualValue()");h.setAttribute("type","color");h.className="form-control showAllInput";$(h).css("display","none");var r=$(this).find(".lessonHeader").css("background-color");$(h).val(rgb2hex(r));b.appendChild(c);b.appendChild(d);b.appendChild(e);
b.appendChild(l);b.appendChild(f);b.appendChild(g);b.appendChild(h);a.appendChild(b);$(this).find(".lecPracHeader").each(function(){var b=document.createElement("div");b.className="section contentDivDiv";var c=document.createElement("div");c.className="contentDivDivDraggableDiv progress-bar-striped bg-success";c.style.opacity="0";var d=document.createElement("div");d.className="contentDivDivRight";var e=document.createElement("div");e.className="leftDiv";var l=document.createElement("p");l.appendChild(document.createTextNode("Lesson/ICA Type"));
var f=document.createElement("select");f.setAttribute("onchange","setActualColour(this)");f.className="inputDiv custom-select";var g=document.createElement("option");g.appendChild(document.createTextNode("Lecture"));g.setAttribute("value","Lecture");var h=document.createElement("option");h.appendChild(document.createTextNode("Practical"));h.setAttribute("value","Practical");var k=document.createElement("option");k.appendChild(document.createTextNode("Tutorial"));k.setAttribute("value","Tutorial");
var p=document.createElement("option");p.appendChild(document.createTextNode("Remark"));p.setAttribute("value","Remark");var m=document.createElement("option");m.appendChild(document.createTextNode("E-Learning"));m.setAttribute("value","E-Learning");var n=document.createElement("option");n.appendChild(document.createTextNode("In Course Assessment"));n.setAttribute("value","In Course Assessment");f.appendChild(g);f.appendChild(h);f.appendChild(k);f.appendChild(p);f.appendChild(m);f.appendChild(n);
$(f).val($(this).find(".lecPracDiv :first-child").text());g=document.createElement("input");g.setAttribute("onchange","setActualValue()");g.setAttribute("type","color");g.className="form-control";$(g).css("display","none");h=$(this).find(".lecPracDiv").css("background-color");$(g).val(rgb2hex(h));e.appendChild(l);e.appendChild(f);e.appendChild(g);l=document.createElement("div");l.className="flex rightDiv";f=document.createElement("div");f.className="page1Content";g=document.createElement("p");g.appendChild(document.createTextNode("Title"));
h=document.createElement("div");h.contentEditable="true";h.className="inputDiv contenteditableBr form-control";h.setAttribute("onkeyup","divToInput(this)");h.setAttribute("onkeydown","divToInput(this)");k=document.createElement("input");k.setAttribute("onkeyup","inputToDiv(this)");k.setAttribute("onkeydown","inputToDiv(this))");k.setAttribute("type","text");$(h).html($(this).find(".lessonPlanContent .lessonPlanContentP").html());$(k).val($(this).find(".lessonPlanContent .lessonPlanContentP").html());
$(k).css("display","none");p=document.createElement("p");p.appendChild(document.createTextNode("Topics"));m=document.createElement("div");m.contentEditable="true";m.className="inputDiv form-control";m.setAttribute("onkeyup","divToInput(this)");m.setAttribute("onkeydown","divToInput(this)");n=document.createElement("textarea");n.setAttribute("onkeyup","inputToDiv(this)");n.setAttribute("onkeydown","inputToDiv(this)");$(n).css("display","none");var q=$(this).find(".lessonPlanContent ul")[0].outerHTML.trim().replace(/\t/g,
"");$(m).html(q);$(n).val(q);$(m).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});f.appendChild(g);f.appendChild(h);f.appendChild(k);f.appendChild(p);f.appendChild(m);f.appendChild(n);l.appendChild(f);f=document.createElement("button");f.className="closeImg close";f.setAttribute("onclick","removeLessonContent(this)");f.setAttribute("type","button");f.setAttribute("aria-label","Close");g=document.createElement("span");g.setAttribute("aria-hidden","true");
g.innerHTML="&times;";f.appendChild(g);d.appendChild(e);d.appendChild(l);b.appendChild(c);b.appendChild(d);b.appendChild(f);a.appendChild(b)});b=document.createElement("div");b.className="addLessonContent";c=document.createElement("p");c.appendChild(document.createTextNode("Add New Lesson/ICA"));d=document.createElement("i");e=document.createElement("button");e.className="closeImg close";l=document.createElement("span");b.setAttribute("onclick","addLessonContent(this)");d.className="fas fa-plus-circle";
e.setAttribute("onclick","removeLessonContent(this)");e.setAttribute("type","button");e.setAttribute("aria-label","Close");l.setAttribute("aria-hidden","true");l.innerHTML="&times;";e.appendChild(l);b.appendChild(d);b.appendChild(c);a.appendChild(b);a.appendChild(e);$("#page1").append(a)});a=document.createElement("div");c=document.createElement("i");d=document.createElement("p");a.id="addLessonSection";a.className="addLessonContent";a.setAttribute("onclick","addLessonSection(this)");a.style.color=
"white";c.className="fas fa-plus-circle";d.appendChild(document.createTextNode("Add New Lesson"));a.appendChild(c);a.appendChild(d);c=document.createElement("div");c.className="footerSection";d=document.createElement("p");d.appendChild(document.createTextNode("Footnote"));b=document.createElement("div");b.contentEditable="true";b.className="inputDiv contenteditableBr form-control";b.setAttribute("onkeyup","divToInput(this)");b.setAttribute("onkeydown","divToInput(this)");e=document.createElement("input");
e.setAttribute("type","text");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.id="lessonPlanFooter";$(b).html($("#lessonPlanTemplate .sub").html());$(e).val($("#lessonPlanTemplate .sub").html());$(e).css("display","none");c.appendChild(d);c.appendChild(b);c.appendChild(e);d=document.createElement("br");b=document.createElement("div");b.style.display="flex";b.style.flexDirection="column";e=document.createElement("button");e.appendChild(document.createTextNode("Generate HTML for BlackBoard"));
e.setAttribute("onclick","generateHTML()");e.className="btn btn-primary";var f=document.createElement("button");f.appendChild(document.createTextNode("Save As HTML (For Reimport)"));f.setAttribute("onclick","saveHTMLFile()");f.className="btn btn-secondary";var g=document.createElement("button");g.appendChild(document.createTextNode("Show All Hidden HTML"));g.setAttribute("onclick","showAllInput(this)");g.className="btn btn-secondary";b.appendChild(e);b.appendChild(f);b.appendChild(g);e=document.getElementById("page1");
e.appendChild(a);e.appendChild(c);e.appendChild(d);e.appendChild(b);contentEditableBr();makeSortable()}
function recreatePage2(){$("#page2").empty();var a=document.createElement("div");a.id="lessonPlanTemplate";var c=document.createElement("p");c.appendChild(document.createTextNode("Instructors Details"));var d=document.createElement("div"),b=$("#paragraphTextarea").val();$(d).html(b);c.className="bold underline";d.id="instructorsDetails";a.append(c);a.append(d);$(".mainSection").each(function(){var b=document.createElement("div"),c=document.createElement("div");c.style.backgroundColor=$(this).find(".lessonTitle > :last-child").val();
var d=document.createElement("p");$(d).html($(this).find(".lessonTitleInput").val());var k=document.createElement("p");$(k).html($(this).find(".lessonSubtitleInput").val());b.className="lesson";c.className="lessonHeader";d.className="bold";k.className="em";c.appendChild(d);c.appendChild(k);b.appendChild(c);$(this).find(".contentDivDiv").each(function(){var a=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(c).css("background-color",$(this).find(".leftDiv input").val());
$(d).html($(this).find(".leftDiv :nth-child(2)").val());c.appendChild(d);var e=document.createElement("div"),f=document.createElement("p");$(f).html($(this).find(".rightDiv .page1Content .inputDiv").eq(0).html());var g=$(this).find(".rightDiv .page1Content .inputDiv").eq(1).html();$(e).html(g);a.className="lecPracHeader";c.className="lecPracDiv";d.className="bold";e.className="lessonPlanContent";f.className="lessonPlanContentP";$(e).prepend(f);a.appendChild(c);a.appendChild(e);b.appendChild(a)});
a.append(b)});c=document.createElement("p");$(c).html($("#lessonPlanFooter").val());c.className="sub";a.append(c);$("#page2").append(a)}function setInputValue(){recreatePage1()}function setActualValue(){recreatePage2()}function setActualColour(a){var c=a.value,d=JSON.parse(colourTemplate);d[c]&&$(a).next().val(d[c]);recreatePage2()}function generateHTML(){$("#popupDiv").modal("show");$("#popup .modal-body textarea").val($("#page2").html().trim())}
function closePopup(){$("#popupDiv").modal("hide");$("#popup .generateHTMLRedText").css("display","none")}function copyToClipboard(){$("#popup .modal-body textarea")[0].select();document.execCommand("copy");$("#popup .generateHTMLRedText").css("display","block")}function copyCommand(){var a=document.createElement("textarea");$(a).text(selectedText);$("#masterDiv").append(a);$(a)[0].select();document.execCommand("copy");$(a).remove()}
function checkOverlapLink(a){a=htmlEncode(a);var c=focusedInput;startIndex=c.next().val().indexOf(a);var d=escape("<a href="),b=escape("</a>");if((new RegExp("("+d+").*("+escape(a)+").*("+b+")")).test(escape(c.next().val())))return alert("Error! You already made this a link."),!1;if(-1!==startIndex)return!0;alert("Error! Make sure the text selected is not overlapping with another link.");return!1}
function promptLink(){0<selectedText.length&&checkOverlapLink(selectedText)&&($("#linkInput").val("https://"),$("#linkBoxOptions").text("Webpage"),$("#linkBoxDiv").modal("show"))}function hideLinkBox(){$("#linkBoxDiv").modal("hide");changeInputBoxSelection(1)}function hideExcelBox(){$("#excelSelectInput").removeClass("is-invalid");$("#excelSelectInput").removeClass("is-valid");$("#inputGroupFile01").val(null);$("#uploadedFileName").html("Choose file");$("#excelBoxDiv").modal("hide")}
function changeInputBoxSelection(a){$(".dropdown-menu > .active.dropdown-item")[0].classList.remove("active");var c=$("#linkBoxOptions"),d=$("#linkInput");switch(a){case 1:c.text("Webpage");d[0].setAttribute("placeholder","https://");d.val("https://");$(".dropdown-menu > a:first-child")[0].classList.add("active");break;case 2:c.text("Email");d[0].setAttribute("placeholder","example@nyp.edu.sg");d.val("");/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&
d.val(htmlEncode(selectedText));$(".dropdown-menu > a:nth-child(2)")[0].classList.add("active");break;case 3:c.text("Javascript"),d[0].setAttribute("placeholder","alert('Hello')"),d.val(""),$(".dropdown-menu > a:nth-child(4)")[0].classList.add("active")}}
function checkAndDisplayAlert(){if($("#linkInput").val()){var a=document.createElement("div");a.className="alert alert-warning fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var c=document.createElement("p"),d=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML=
"&times;";b.appendChild(e);d.appendChild(b);a.appendChild(c);a.appendChild(d);d=$("#linkInput").val();b=$("#linkBoxOptions").text();"Webpage"===b?/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(d)?closeAlert():(closeAlert(),c.appendChild(document.createTextNode("The URL entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):"Email"===b&&(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(d)?
closeAlert():(closeAlert(),c.appendChild(document.createTextNode("The email entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)))}}function whichLinkSelection(){var a=$("#linkBoxOptions").text();if("Webpage"===a)return"";if("Email"===a)return"mailto:";if("Javascript"===a)return"javascript:";alert("Unexpected error");return null}
function convertToLink(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var c=document.createElement("p"),d=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML="&times;";b.appendChild(e);
d.appendChild(b);a.appendChild(c);a.appendChild(d);if(d=$("#linkInput").val()){if(""===whichLinkSelection()){if(!/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(d)&&!confirm("The URL entered does not match the format. Do you want to continue?"))return c.appendChild(document.createTextNode("The URL entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1}else if("mailto:"===
whichLinkSelection()&&!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&!confirm("The email entered does not match the format. Do you want to continue?"))return c.appendChild(document.createTextNode("The email entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1;b=htmlEncode(selectedText);
var f=focusedInput;e=f.html();d=whichLinkSelection()?"<a href='"+whichLinkSelection()+$("#linkInput").val()+"' target='_blank'>"+b+"</a>":"<a href='"+$("#linkInput").val()+"' target='_blank'>"+b+"</a>";startIndex=f.next().val().indexOf(b);var g=escape("<a href="),k=escape("</a>");(new RegExp("("+g+").*("+escape(b)+").*("+k+")")).test(escape(f.next().val()))?(c.appendChild(document.createTextNode("Error! You already made this a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):-1!==
startIndex?(a=e.substring(0,startIndex),c=e.substring(startIndex+b.length),a=a+d+c,focusedInput.next().val(a),focusedInput.html(focusedInput.next().val()),setActualValue()):(c.appendChild(document.createTextNode("Error! Make sure the text selected is not overlapping with another link.")),$("#linkBox > .modal-content > .modal-body").prepend(a));hideLinkBox()}else c.appendChild(document.createTextNode("Please enter a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)}
function divToInput(a){$(a).next().val(a.innerHTML);setActualValue()}function inputToDiv(a){$(a).prev().html(a.value);setActualValue()}
function saveHTMLFile(){try{new Blob;var a=prompt("Please enter filename:","BlackBoard Lesson Plan");if(a){var c=document.getElementById("lessonPlanTemplate").outerHTML.toString(),d=new Blob([c],{type:"text/html;charset=utf-8"});saveAs(d,a+".html")}}catch(e){a=document.createElement("div");a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";a.style.backgroundColor="rgba(25,25,25,0.6)";a.id="saveFileAlertBackground";c=document.createElement("div");c.className=
"alert alert-danger alert-dismissible fade show";c.setAttribute("role","alert");c.style.position="absolute";c.style.top="40%";c.style.left="20%";c.style.width="60%";c.style.height="20%";d=document.createElement("p");d.innerHTML="<strong>File saving not supported</strong><br>To save the file, press <kbd><kbd>ctrl</kbd> + <kbd>s</kbd></kbd>";var b=document.createElement("button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","close");b.appendChild(document.createTextNode("Close"));
b.className="btn btn-primary";b.onclick=function(){$("#saveFileAlertBackground").remove()};c.appendChild(d);c.appendChild(b);a.appendChild(c);$("#masterDiv").append(a);console.log("Error message: "+e)}}
function showAllInput(a){notClicked?($(".inputDiv").next().css("display","block"),$("textarea:not(#popup textarea)").css("display","block"),$(".showAllInput").css("display","block"),a.innerHTML="Hide All Hidden HTML",notClicked=!1):($(".inputDiv").next().css("display","none"),$("textarea:not(#popup textarea)").css("display","none"),$(".showAllInput").css("display","none"),a.innerHTML="Show All Hidden HTML",notClicked=!0)}
function checkImage(){for(i=0;i<$("#instructionPageContent > .instructionPageContentContents").length;i++)getInstructionGif(i)}
function getInstructionGif(a){var c=$("#instructionPageContent > .instructionPageContentContents").eq(a).find("img")[0];if($(window).width()>$(window).height()){var d="images/LessonPlanGenerator/Desktop/addNewICA.gif";var b="images/LessonPlanGenerator/Desktop/addNewLesson.gif";var e="images/LessonPlanGenerator/Desktop/removingLesson.gif";var f="images/LessonPlanGenerator/Desktop/sorting.gif";var g="images/LessonPlanGenerator/Desktop/link.gif";var k="images/LessonPlanGenerator/Desktop/changingColour.gif"}else d=
"images/LessonPlanGenerator/Mobile/M-addNewICA.gif",b="images/LessonPlanGenerator/Mobile/M-addNewLesson.gif",e="images/LessonPlanGenerator/Mobile/M-removingLesson.gif",f="images/LessonPlanGenerator/Mobile/M-sorting.gif",g="images/LessonPlanGenerator/Mobile/M-link.gif",k="images/LessonPlanGenerator/Mobile/M-changingColour.gif";switch(a){case 0:c.src=d;break;case 1:c.src=b;break;case 2:c.src=e;break;case 3:c.src=f;break;case 4:c.src=g;break;case 5:c.src=k}}
function instructionPageButtonDivNext(a){var c=document.getElementById("instructionPageContent").children;for(i=0;i<c.length;i++){var d=c[i];i===c.length-2&&($(a).prev().text("Finish"),$(a).prev()[0].className="btn btn-primary",$(a).remove());if("block"===$(d).css("display")){getInstructionGif(i+1);d.style.display="none";c[i+1].style.display="block";break}}}function checkEnterKey(a){if(13===a.keyCode)return document.execCommand("insertHTML",!1,"<br /><br />"),!1}
function contentEditableBr(){$(document).off("keydown",".contenteditableBr",checkEnterKey);$(document).on("keydown",".contenteditableBr",checkEnterKey)}function selectAll(a){a.setSelectionRange(0,a.value.length)}var hexDigits="0123456789abcdef".split("");function rgb2hex(a){return(a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/))?"#"+hex(a[1])+hex(a[2])+hex(a[3]):"#000000"}function hex(a){return isNaN(a)?"00":hexDigits[(a-a%16)/16]+hexDigits[a%16]}
function htmlEncode(a){return $("<div/>").text(a).html()}function htmlDecode(a){return a.replace(/&#(\d+);?/g,function(a,d){return String.fromCharCode(d)})};
